### ISSUE TITLE
Move Add Flow button to top menu bar

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#101]
I think its a little bit confusing that "Add flow" button is soo prominent on the screen that you think you need to click this button to add a new step. Instead you need to however the mouse at the EIP and then the + sign appears.

Should we move "Add flow" to the top right where the other buttons are "Copy" and "Save".

And it can be named "Add new flow" then you better understands its a new flow (route) and not a ste
<img width="2028" alt="Screenshot 2021-11-16 at 09 30 15" src="https://user-images.githubusercontent.com/477100/141949341-74889053-1757-482a-88c8-b1c4355d7c2e.png">
p

**Comment by mgubaidullin** [comment]
The button was in the toolbar from the beginning, but then it was moved to the diagram to make it consistent with VSCode version. in VSCode toolbar customization possibilities are limited to make a well noticed button there. 

<img width="1203" alt="Screen Shot 2021-11-16 at 7 38 27 AM" src="https://user-images.githubusercontent.com/1379213/141986655-73e0d948-f456-461c-859f-011b8d0f49a5.png">

**Comment by davsclaus** [comment]
Ah okay, so maybe for standalone if possible to have a square around the flow/route so it looks more similar to vs code, where the "Add flow" button is outside the square and therefore better indicate you create a new flow.

And also maybe rename "Add flow" -> "New flow"

**Comment by mgubaidullin** [comment]
We could also make plus button for `from` element always visible

![Screen Shot 2021-11-16 at 8 04 21 AM](https://user-images.githubusercontent.com/1379213/141990451-29d4ac13-e5d4-483c-b4a6-8f4b0d03c5e9.png)


![Screen Shot 2021-11-16 at 8 04 42 AM](https://user-images.githubusercontent.com/1379213/141990469-c52daf24-dfd9-42fd-aa82-cc3f04012749.png)
