### ISSUE TITLE
Panel to configure options has both advanced properties and advanced parameters

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1014]
I wonder why or should they not just be merged into a one - Advanced parameters
The screenshot is AWS DynamoDB component

<img width="1349" alt="Screenshot 2023-12-06 at 06 55 51" src="https://github.com/apache/camel-karavan/assets/477100/2c304b81-da27-4613-a055-d4478633cdcf">

**Comment by mgubaidullin** [comment]
Advanced parameters are advanced parameters of the Component.

Advanced properties are advanced properties of the EIP used to call the Component (`to`)
