### ISSUE TITLE
Creating a new flow - CRD what does it mean

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#103]
When creating a new flow, there is a [x] for CRD.

I think end users will not understand what it means. We should have a description what it means to turn this on or off.

**Comment by mgubaidullin** [comment]
Description added

![Screen Shot 2021-11-16 at 12 58 23 PM](https://user-images.githubusercontent.com/1379213/142040285-e900bbcb-4638-4a1b-84d6-aa66a1c3d964.png)
