### ISSUE TITLE
org.json package not found

### ISSUE THREAD

**Issue by samar-elsayed** [apache/camel-karavan#1037]
Hi,

in Karavan UI,  I am trying to import org.json.* and used **mvn:org.json:json:20231013** or *org.json:json:20231013**  inside **camel.jbang.dependencies** but when trying to run the project, it gives me **package not found** and I can't see any line in logs referring to trying to download the package.

![image](https://github.com/apache/camel-karavan/assets/22873802/b363f96a-e16b-4bb8-8e6c-80c28970e153)
![image](https://github.com/apache/camel-karavan/assets/22873802/92f74fec-c300-4271-ba57-e907d4486026)

so please let me know what should I do to make it work
Thanks!

**Comment by mgubaidullin** [comment]
What Karavan version do you use?

**Comment by samar-elsayed** [comment]
@mgubaidullin version 4.1.0

**Comment by mgubaidullin** [comment]
Could you try with 4.3.0 ?

**Comment by samar-elsayed** [comment]
Thanks! this has solved it
