### ISSUE TITLE
JBang run mode

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#104]
We should get this working. After installing jbang (such as via sdk) then we should make jbang run via its alias

Today it runs as
```
~/workspace/camel-k/examples/languages main ❯ CamelJBang run routes.yaml --max-messages=10 --debug-level=info
zsh: command not found: CamelJBang
```

But that does not work. You have then to copy the CamelJBang.java source file to same dir, rename to not have .java and make it executable. And fix the RELEASE to say 3.13.0.

But if we run via the alias then it should run with the latest release

```
jbang CamelJBang@apache/camel run routes.yaml --max-messages=10 --debug-level=info
```

**Comment by davsclaus** [comment]
<img width="1630" alt="Screenshot 2021-11-16 at 11 11 20" src="https://user-images.githubusercontent.com/477100/141966031-203fe0a5-0f58-4e97-a7ae-4476e2e536ba.png">

**Comment by davsclaus** [comment]
@orpiske we need to get the CamelJBang alias to work with the new 3.13.0 release.

**Comment by davsclaus** [comment]
So you can say

```
jbang CamelJBang@apache/camel run routes.yaml
```

**Comment by orpiske** [comment]
That's very strange. It's it a caching issue on `$HOME/.jbang/cache`? I will take a look.

**Comment by orpiske** [comment]
@davsclaus what does it happen if you run this?

`rm -rf ~/.jbang/cache  && jbang app install --force CamelJBang@apache/camel && CamelJBang --help`

**Comment by davsclaus** [comment]
After running the command, and starting a new shell

```
~/workspace ❯ CamelJBang --help
[jbang] Resolving dependencies...
[jbang] Loading MavenCoordinate [org.apache.camel:camel-bom:pom:RELEASE]
[jbang] [ERROR] Unable to collect/resolve dependency tree for a resolution due to: Failed to collect dependencies at org.apache.camel:camel-bom:pom:RELEASE, caused by: Failed to resolve version for org.apache.camel:camel-bom:pom:RELEASE
[jbang] Run with --verbose for more details
```

**Comment by davsclaus** [comment]
We could maybe update the github source to say 3.13.0 instead of RELEASE as jbang grabs the BLOB from the main branch as a workaround

**Comment by orpiske** [comment]
> We could maybe update the github source to say 3.13.0 instead of RELEASE as jbang grabs the BLOB from the main branch as a workaround

That's very strange. I couldn't reproduce it locally. The good news is that we can easily override this. We can run something like:

`rm -rf ~/.jbang/cache && jbang app install --force CamelJBang@apache/camel && jbang -Dcamel.jbang.version=3.13.0 CamelJBang@apache/camel --help`

**Comment by davsclaus** [comment]
Ah yeah if we specify the version in command line, then @mgubaidullin can make karavan do that. And then maybe add a setting somewhere where you can specify the version to use, if the default version is not what you want

**Comment by davsclaus** [comment]
Using `jbang ...` makes it easier as the end user does not need to have to install CamelJBang as an app. But just install jbang and make sure jbang --version works.

**Comment by orpiske** [comment]
The RELEASE is there to avoid the problem we had on 3.12 release, where it [did not replace the stable](https://github.com/apache/camel/blob/camel-3.12.0/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java#L21) version during the release process. For 3.13 and newer, we basically instruct jbang to use the [latest released version](https://github.com/apache/camel/blob/main/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java#L21) by default. 

One alternative would be to manually do the change during the release process, but I am afraid it would be error prone.

**Comment by orpiske** [comment]
> Using `jbang ...` makes it easier as the end user does not need to have to install CamelJBang as an app. But just install jbang and make sure jbang --version works.

I think that's a good approach. I have a feature request for jbang to introduce a new extension point, so it would be possible to run Camel K java routes directly. This would also render the CamelJBang script unnecessary ... so it would be better to not rely to much on it.

**Comment by mgubaidullin** [comment]
Camel vesion could be set the same way as other CamelJBang settings

<img width="1160" alt="Screen Shot 2021-11-16 at 8 36 16 AM" src="https://user-images.githubusercontent.com/1379213/141995241-8233b257-824f-46a8-8a7b-e6356796f6e9.png">

**Comment by mgubaidullin** [comment]
@davsclaus @orpiske if you want to test the latest (and sometimes greatest) VSCode extension before it is published to Marketplace, then you could find it in the Actions Artifacts ex. https://github.com/apache/camel-karavan/actions/runs/1467051244

**Comment by davsclaus** [comment]
Thanks I have installed it and it works with jbang now.
