### ISSUE TITLE
User should be able to limit resources for integration containers in docker

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1052]
ex:

```
    cpus: "0.5"
    mem_reservation: "10M"
    mem_limit: "250M"
```

**Comment by mgubaidullin** [comment]
@vidhyasagarj could you please take a look on this one? If yes, please add a comment, then I can assign you to the issue

**Comment by vidhyasagarj** [comment]
@mgubaidullin, Sure, I will propose a solution approach and take your feedback.

**Comment by mgubaidullin** [comment]
1. Karavan in Docker adds `docker-compose.yaml` (from snippets) file for every project created.
2. When user deploys project Karavan uses `docker-compose.yaml` from the project folder and applies to Docker.
3. There are DockerCompose model in https://github.com/apache/camel-karavan/blob/main/karavan-app/src/main/java/org/apache/camel/karavan/model/DockerCompose.java and converted Yaml->DockerCompose https://github.com/apache/camel-karavan/blob/main/karavan-app/src/main/java/org/apache/camel/karavan/code/DockerComposeConverter.java


We need to add these limit resources to the model (and converter if needed)
Also we need to set these limit resources when create container https://github.com/apache/camel-karavan/blob/8a37d39f3788641cdd7e21b5584f6426a994553a/karavan-app/src/main/java/org/apache/camel/karavan/docker/DockerService.java#L187C22-L187C48

**Comment by vidhyasagarj** [comment]
@mgubaidullin So, if the user wants to change the resource limits from project to project, how will this work ?

**Comment by mgubaidullin** [comment]
![change-limits](https://github.com/apache/camel-karavan/assets/1379213/ae349045-03a6-40f0-9487-983cf2f74810)

**Comment by mgubaidullin** [comment]
@vidhyasagarj thanks.
I made a mistake. It looks like the format was changed in the latest docker-compose https://docs.docker.com/compose/compose-file/compose-file-v3/#resources

```
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20
```

**Comment by vidhyasagarj** [comment]
Noted @mgubaidullin, Will make the change accordingly. Any plans for adding this feature for kubernetes

**Comment by mgubaidullin** [comment]
In Kubernetes it is already supported by adding deployment.jkube.yaml file with resource fragment to the project

**Comment by vidhyasagarj** [comment]
Seems like the current **docker-java** api only supports the compose v1 parameters like `cpus`, `cpu_shares/percent`, `mem_limits`, `mem_reservations` etc.

it does not specifically support CPU reservations. Any suggestions on how you want this implementation

**Comment by mgubaidullin** [comment]
Lets keep as it is done. Thanks!
The best solution would be to contribute this stuff to docker-java ;-)
