### ISSUE TITLE
Integrations unable to refer files in project folder in dev mode. 

### ISSUE THREAD

**Issue by vidhyasagarj** [apache/camel-karavan#1082]
Example:

   - Create/upload a flatpack mapping xml, test say test.mapping.xml
   - Create a simple route from(FTP)->unmarshal(Flatpack(test.mapping,xml))->log($body)
   - Run the integration in dev mode and upload file via FTP for process, throws File Not Found example for test.mapping.xml

Whereas the sample works fine when dockerized from the project. I understand the issue is because the files are stored in Infinispan and hence the route cannot refer to the same file from jbang runner classpath.

Do let me know if you have any suggestions, I can work on this.

**Comment by davsclaus** [comment]
It may be due to this to be fixed in Camel 4.4
https://issues.apache.org/jira/browse/CAMEL-20354

**Comment by davsclaus** [comment]
closing old ticket
