### ISSUE TITLE
Issue running Karavan App in dev mode with quarkus:dev 

### ISSUE THREAD

**Issue by vidhyasagarj** [apache/camel-karavan#1083]
I am facing a strange problem when I try to run the Karavan app in dev mode with the necessary changes on the Windows machine 

I have made basic changes to get things to work on windows 

Changed `package.json` line 6 to 9

```
    "copy-designer": "xcopy ..\\..\\..\\..\\..\\karavan-designer\\src\\designer src\\designer /E/H/Y",
    "copy-knowledgebase": "xcopy ..\\..\\..\\..\\..\\karavan-designer\\src\\knowledgebase src\\knowledgebase /E/H/Y",
    "copy-topology": "xcopy ..\\..\\..\\..\\..\\karavan-designer\\src\\topology src\\topology /E/H/Y",
    "copy-code": "npm run copy-designer &&  npm run copy-knowledgebase &&  npm run copy-topology",

```

Created a new quarkus profile - local as below in `application.properties`

```
# Local
%local.karavan.auth=public
%local.quarkus.oidc.enabled=false
%local.quarkus.http.auth.basic=false
%local.quarkus.security.users.embedded.enabled=false
%local.quarkus.http.auth.permission.authenticated.enabled=false
%local.quarkus.http.auth.permission.public.enabled=false
%local.karavan.image-registry=localhost:5000
%local.karavan.infinispan.hosts=localhost:11222
%local.karavan.git-repository=http://localhost:3000/karavan/karavan.git
%local.karavan.image-registry-install=true
%local.karavan.git-install-gitea=true
%local.quarkus.http.host=localhost
%local.quarkus.http.port=9090
```

Quarkus served the application without any issue and all looks fine to me. 

![image](https://github.com/apache/camel-karavan/assets/36588343/8e62eb4c-03e5-4b2b-b81e-a6e4923b19c6)
![image](https://github.com/apache/camel-karavan/assets/36588343/89c90a7c-ec82-4bc7-a5a9-108936176253)

But when I load the Karavan web the get apis (ex. /public/readiness), keeps loading, not reaching the API at all 
![image](https://github.com/apache/camel-karavan/assets/36588343/8689c7ae-5e90-496e-aa70-67e232ba9438)
![image](https://github.com/apache/camel-karavan/assets/36588343/ecabb3eb-ea27-4ded-a270-7c38c7b88fa2)

Not sure whether it is a Quarkus issue or Windows specific issue.

**Comment by gun2rin** [comment]
Hi, check this out. Maybe this is the same problem? https://github.com/apache/camel-karavan/issues/1066

**Comment by vidhyasagarj** [comment]
Yup that worked @gun2rin  Thanks
