### ISSUE TITLE
Camel 4.4 - Adding back camel-beanio data format

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1084]
The logo for beanio is at
https://github.com/beanio/beanio/blob/main/site/images/logo.png

It would be good to use this logo in the UI

**Comment by mgubaidullin** [comment]
SVG required

**Comment by davsclaus** [comment]
There is an ico file also, maybe we can export this to svg

**Comment by davsclaus** [comment]
![beanio](https://github.com/apache/camel-karavan/assets/477100/a9d6de78-ed35-4667-bfb1-80efd75c398a)

**Comment by mgubaidullin** [comment]
There is no images for data formats. I think it would be too noisy to have them

<img width="428" alt="Screenshot 2024-02-27 at 10 21 05 AM" src="https://github.com/apache/camel-karavan/assets/1379213/4f70b0d2-ceca-4376-92a4-72c1cccbba87">

**Comment by vidhyasagarj** [comment]
Thanks for this @davsclaus
