### ISSUE TITLE
Dev mode run not working in Kubernetes deployment

### ISSUE THREAD

**Issue by mvolf** [apache/camel-karavan#1112]
Running project in dev mode doesn't work in Kubernetes deployment. If I click Run in developer mode button the project starts to run, but no integrations get found (visible in the Routes startup log entry) and the process hangs for tens of seconds. After some time it retries, but the results is the same.

Logs after running in dev mode:
![run](https://github.com/apache/camel-karavan/assets/798213/799a0459-4f97-4f12-a31b-fe78217daa6d)

If I click Reload button while the project is running the needed files (application.properties and all other integration related files) get created and the project starts running successfully. This is the only way to get the project to run in dev mode.

Logs after clicking reload ("Creating file" entries appear after clicking Reload):
![reload](https://github.com/apache/camel-karavan/assets/798213/8b8ee925-d87b-4267-8318-ddf70ea45119)

@mgubaidullin to me it looks like that for Kubernetes deployment (in some cases) project files are not copied to the project pod when running in dev mode. They are copied successfully after a user clicks Reload button. Any ideas why this could be happening?

P.S.
In local docker depyloment dev mode works as expected, which points to the issue being only somewhere in the KuberentesService.

**Comment by mgubaidullin** [comment]
Any error messages in karavan-web pod?

**Comment by mvolf** [comment]
Nothing in the logs, no. Sorry, forgot to mention that.

**Comment by mvolf** [comment]
@mgubaidullin one more thing: I just connected to the project pod after I ran the dev mode and there was not even one file from the project in /karavan/code folder. This goes in line with my assumption that project file copying doesn't work as expected in some cases for Kubernetes deployment.

**Comment by mvolf** [comment]
Closing this, since the issue was with the implementation of the Kubernetes deployment
