### ISSUE TITLE
Error when upload file

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1114]
```
ERROR
Cannot read properties of null (reading 'target')
TypeError: Cannot read properties of null (reading 'target')
    at Object.onChange (http://localhost:8080/static/js/bundle.js:369829:26)
    at onFileInputChange (http://localhost:8080/static/js/bundle.js:34817:32)
    at onDropAccepted (http://localhost:8080/static/js/bundle.js:46165:77)
    at http://localhost:8080/static/js/bundle.js:168356:7
    at http://localhost:8080/static/js/bundle.js:168396:9
ERROR
Cannot read properties of null (reading 'target')
TypeError: Cannot read properties of null (reading 'target')
    at Object.onChange (http://localhost:8080/static/js/bundle.js:369829:26)
    at onDataChange (http://localhost:8080/static/js/bundle.js:34821:32)
    at http://localhost:8080/static/js/bundle.js:46170:71
    ```

**Comment by mgubaidullin** [comment]
@mvolf could you please take a look https://github.com/apache/camel-karavan/blob/c73a0411223357bcfdd2342792aff77a5bf65ec3/karavan-web/karavan-app/src/main/webui/src/project/files/UploadFileModal.tsx#L178

`_event` is undefined there, how react-hook-forms should be configured?

**Comment by mvolf** [comment]
When do you get this exception? I can't reproduce upload file not working. Can you please give me the steps to reproduce the issue?

**Comment by mvolf** [comment]
Which browser are you using? I can't reproduce it in Chromium and Firefox. I'm also on Karavan 4.3.0, not latest master.

**Comment by mgubaidullin** [comment]
Sorry. The issue with the latest code from main after file import validation

**Comment by mvolf** [comment]
It's interesting that for me this only fails with latest Chromium version (Brave and Firefox work as expected). As far as I can remember, I tested this with Chromium when I implemented it and it worked back then.
I'll take a look at what can be done...

**Comment by mvolf** [comment]
@mgubaidullin Can you please close this issue if the merged PR fixed it for you?

**Comment by mgubaidullin** [comment]
Thanks @mvolf
