### ISSUE TITLE
JBang live reload

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#112]
We have support for live reload in Camel 3.14.0
https://issues.apache.org/jira/browse/CAMEL-17206

So you can run
```
jbang -Dcamel.jbang.version=3.14.0-SNAPSHOT CamelJBang@apache/camel run my-route.yaml --reload
```

**Comment by mgubaidullin** [comment]
How it works with `--max-messages=XX` ?

**Comment by davsclaus** [comment]
Max messages will still be active, so if you set it to 10 seconds then it will stop after that time, regardless of if reloaded or not.

Are you looking for a way to "restart the max messages" on reload?

**Comment by mgubaidullin** [comment]
Yes, I thought if `--max-messages` and `--reload` both set than after max-messages processing stops but don't exit.
And after changes in the code it reloads and process till next max-messages

**Comment by davsclaus** [comment]
I wonder if we should name the option `--dev` so its more similar to quarkus with its `mvn quarkus:dev` maven command?

**Comment by davsclaus** [comment]
Reset duration counters: https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-17215

**Comment by mgubaidullin** [comment]
`reload` option has been added

<img width="873" alt="Screen Shot 2021-11-22 at 7 42 30 AM" src="https://user-images.githubusercontent.com/1379213/142865976-7df1002b-6e05-462d-891c-876adf3f537a.png">

**Comment by mgubaidullin** [comment]
If I use the following command 
```
jbang -Dcamel.jbang.version=3.14.0-SNAPSHOT CamelJBang@apache/camel run timer-demo.yaml --max-messages=10 --logging-level=info --reload
```

After 10 messages route stops and program exit. I thought if we could just stop route after `-max-messages` without exit

**Comment by davsclaus** [comment]
Ah but max duration(s) has always been to terminate the JVM application.

**Comment by davsclaus** [comment]
Created a ticket
https://issues.apache.org/jira/browse/CAMEL-17223

**Comment by mgubaidullin** [comment]
We could terminate if no `reload` option or just stop route if there is a `reload` option

**Comment by mgubaidullin** [comment]
Are max-messages and max duration the same option?

**Comment by davsclaus** [comment]
No, one is X number of messages in total processed, and the other is after X seconds (time). And there is also a 3rd about being idle (eg no messages after X time)

**Comment by davsclaus** [comment]
Okay now we stop routes when using `reload` and shutdown JVM if not.

**Comment by mgubaidullin** [comment]
@davsclaus route does not start after stop if change log parameters. ex. https://youtu.be/lAVERmz8tu4

**Comment by davsclaus** [comment]
@mgubaidullin okay so its a problem with the Kamelet EIP. I need to dig deeper to find the bug

If you use this, then it works
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: my-camel-k.yaml
spec:
  flows:
    - from:
        uri: "kamelet:timer-source"
        parameters:
          message: Hello Camel K3
          period: 3000
        steps:
          - to: "log:sink?showHeaders=false"
```

**Comment by davsclaus** [comment]
You can also use `kamelet` in the to, eg

```
          - to: "kamelet:log-sink?showHeaders=false"
```

**Comment by davsclaus** [comment]
I created a ticket
https://issues.apache.org/jira/browse/CAMEL-17228

**Comment by davsclaus** [comment]
Okay I have fixed that reload issue (there is maybe a little bit too much logging noise about stopping/shutdown routes)

**Comment by mgubaidullin** [comment]
Now it works fine for me. Thanks @davsclaus 
Now I need to fix [that issue](https://github.com/apache/camel-karavan/issues/128) to make reload even better.
I think this issue could be close.
