### ISSUE TITLE
Camel 4.5 - EIPs that support exchange properties are now in camel-catalog

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1133]
https://issues.apache.org/jira/browse/CAMEL-20381

For example Aggregate EIP
https://github.com/apache/camel/blob/main/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/aggregate.json#L47

There is a new `exchangeProperties` in the model json files. If an EIP has no support then there are no exchangeProperties at all in the json.

Also notice that Aggregate is special as it has 3 consumer (input) that end user can set to control the EIP. All the others are producer based, eg output so they come after the EIP when being routed.

For example the CamelAggregatedCompletedBy that tells the user how the exchange was completed (size, timeout etc.)

**Comment by mgubaidullin** [comment]
<img width="1151" alt="Screenshot 2024-04-11 at 11 07 13 AM" src="https://github.com/apache/camel-karavan/assets/1379213/ad5c92a7-fd2e-434c-85ca-0c69e1a5434a">
