### ISSUE TITLE
Add support for dynamic properties

### ISSUE THREAD

**Issue by bartoszpop** [apache/camel-karavan#1138]
We created a kamelet for the OAuth2 authentication that accepts a list of key-value pairs provided by the user, and we tried to use type=object with additionalProperties defined in [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form) (used by OpenShift), but it does not render as Karavan uses [PatternFly](https://github.com/apache/camel-karavan/blob/main/karavan-web/karavan-app/src/main/webui/src/designer/property/property/KameletPropertyField.tsx). Is there any way to have a dynamic field with key-value pairs or do you plan to add this feature? Similarly for the arrays. Syntax could be the same as for react-jsonschema-form, e.g.

    spec:
      definition:
        title: "Kamelet"
        description: This is a kamelet.
        type: object
        properties:
          title: Form
          type: object
          properties:
            someProperty:
              title: Key-Value Pairs
              type: object
              additionalProperties:
                type: string

We use kamelets extensively and it is a common scenario where properties are not static.

**Comment by oscerd** [comment]
It would be a good addition to the official catalog btw

**Comment by mgubaidullin** [comment]
Can not be solved in Karavan, because Karavan follows Kamelet spec
