### ISSUE TITLE
Error while building Karavan Web Application

### ISSUE THREAD

**Issue by Praval791** [apache/camel-karavan#1147]
### System Configurations
```shell
Maven home: C:\apache-maven-3.9.6
Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\jdk-17.0.2
Default locale: en_IN, platform encoding: Cp1252
OS name: "Windows 10", version: "10.0", architecture: "amd64", family: "Windows"
```

### Issue Description
When attempting to build the Karavan web application, the first step involves running the following command:

```shell
mvn clean compile exec:java -Dexec.mainClass="org.apache.camel.karavan.generator.KaravanGenerator" -f karavan-generator
```

Encountered errors:
- **When executed in the root directory:**
  ![Error 1](https://github.com/apache/camel-karavan/assets/94207665/d88becc8-0224-479f-9799-03995733cb4c)

- **When executed in the 'karavan-generator' directory:**
  ![Error 2](https://github.com/apache/camel-karavan/assets/94207665/ab43db2e-e958-4345-b0c7-44efd7840e2e)

- Additionally, after attempting to execute:
    - `mvn clean compile`, which succeeded
    - Following with the initial command, resulted in:
      ![Error 3](https://github.com/apache/camel-karavan/assets/94207665/ee74db40-7d2e-4ccd-9f81-c28b91d85cf8)

The objective is to address these issues and successfully build the Karavan web application.

**Comment by Praval791** [comment]
## Update 
I just changed the Maven version to 3.5.0 and it's working.

### New Issue:
When building the Karavan app as step 3 suggested in this [README](../blob/main/docs/DEV.md):

```shell
mvn clean package -f karavan-app -Dquarkus.profile=public
```

I'm getting this error:
![Error](https://github.com/apache/camel-karavan/assets/94207665/3a1f95b3-cb41-47b0-bfb6-f90d41b90780)

**Suggestion:** Please update the README file and also mention the required version of dependencies.

**Comment by indubabu** [comment]
If you are using Powershell, you will have to add quotes around -D parameters 
[](https://stackoverflow.com/questions/21902668/maven-works-in-cmd-but-not-powershell)

otherwise, you can try with the command prompt.

**Comment by Praval791** [comment]
@indubabu  yes, I have to use CMD, and there was an error in the instructions in the dev README that I fixed yesterday. Now, the README is also updated.

**Comment by vidhyasagarj** [comment]
@Praval791 There is recent change to move the `karavan-app` out to the root and remove the folder `karavan-web`, If you take latest it should work as is for with the old readme. Kindly check.
