### ISSUE TITLE
Upload OpenAPI spec fails

### ISSUE THREAD

**Issue by Premcnathan** [apache/camel-karavan#1163]
**Issue**
Uploading OpenAPI spec is not rendering routes on karavan.space.

**Steps to reproduce**
Upload [testopneapi.json](https://github.com/apache/camel-karavan/files/14493166/testopneapi.json) to "Upload OpenAPI" section of karavan.
![image](https://github.com/apache/camel-karavan/assets/25217533/5fc284f0-403f-4a56-a14d-7bca96c184e2)

**Error**
![image](https://github.com/apache/camel-karavan/assets/25217533/1f9075f2-5f43-4dc3-b2e9-ed974721c1cc)

**Expected**
Rest DSL routes and wrappers with direct endpoint should be created.

**Comment by davsclaus** [comment]
Can you try with other json api files to see if its general or maybe it works with some simpler apis. This can help us track down what is the problem

**Comment by Premcnathan** [comment]
@davsclaus : I could make it work by creating a dummy route in karavan.space and then upload the same OpenAPI spec. Looks like a bug that is asking for a non-empty route.
