### ISSUE TITLE
kubernetes-build.sh is NOT getting updated 

### ISSUE THREAD

**Issue by skumaravelan** [apache/camel-karavan#1170]
Hi, 
I am trying latest version  to update the kubernetes-build.sh and save it and its is not getting updated. Any resolution or troubleshooting steps to resolve this issue?

**Comment by mgubaidullin** [comment]
How to reproduce?

**Comment by skumaravelan** [comment]
1. Install the latest version 
2. make changes to  kubernetes-build.sh on templates folder 
3. and move and push changes to git and files is not getting updated on both editors and git.

**Comment by skumaravelan** [comment]
I tried this latest code, I am not able to update the code editor code .
