### ISSUE TITLE
Docker compose fails

### ISSUE THREAD

**Issue by mechatronics123** [apache/camel-karavan#1173]
[karavan_docker_log.txt](https://github.com/apache/camel-karavan/files/14596080/karavan_docker_log.txt)

Hi there,

I'm striking issues installing Karavan Docker version, can you please have a look at the log and advise potential solution?

Thanks,
Mos

**Comment by mgubaidullin** [comment]
It would be very helpful if you share docker-compose.yaml that you are using

**Comment by davsclaus** [comment]
closing as user did not respond
