### ISSUE TITLE
Gather metrics on usage

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#122]
it would be nice to gather metrics on usage, for instance:
- number of times jbang run is used, how many times it is in success/error. In case of error, to report the error.
- number of times the VS Code Graphical editor is opened
- the share of "plain" yaml and CRD opened in VS Code graphical editor

it will allow to help driving new feature development and to detect common problems users can encounter.

There is this library https://github.com/redhat-developer/vscode-redhat-telemetry. It is collecting metrics on Red Hat Woopra account.
Maybe Apache has its own metric collection also.

**Comment by davsclaus** [comment]
At this time we dont need or want to gather such metrcis
