### ISSUE TITLE
Bug - Tag for 4.4.1 is missing

### ISSUE THREAD

**Issue by vijayrhythm** [apache/camel-karavan#1228]
### Describe the bug

Hi Team,

We couldn't find a tag for 4.4.1 with Open API fix in Karavan Space and now 4.5.0 is available with Camel 4.5.0 upgrades. Please could you help to create a tag for 4.4.1 for April 3rd commit https://github.com/apache/camel-karavan/commit/2f3336abe4e37dbffab1a6c534165029c3b5e3bd    

Thanks,
Vijay

### Steps to reproduce the behavior

1. Tag for 4.4.1 is missing for commit https://github.com/apache/camel-karavan/commit/2f3336abe4e37dbffab1a6c534165029c3b5e3bd

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.4.0

**Comment by mgubaidullin** [comment]
There was no release of Karavan 4.4.1
