### ISSUE TITLE
Karavan 4.5.1 in Docker /  "dcs" is null

### ISSUE THREAD

**Issue by jva70** [apache/camel-karavan#1250]
### Describe the bug

After installation of new version of Karavan in Docker and an attempt to create new project I got:
<img width="466" alt="image" src="https://github.com/apache/camel-karavan/assets/162105086/ea6935cd-4582-439d-a2f9-894ce9bac7c6">

The error can be found also in logs "karavan   | 2024-04-26 19:30:23,081 ERROR [org.apa.cam.kar.api.DevModeResource] (executor-thread-5) java.lang.NullPointerException: Cannot invoke "org.apache.camel.karavan.model.DockerComposeService.getPortsMap()" because "dcs" is null", this time when I try to run a route in Developer mode

### Steps to reproduce the behavior

1. localhost:8080
2. Projects
3. [+] Create
4. Fill in the form and submit

### Variant

Web Application

### Container Management (if applicable)

Docker

### Operating System (if applicable)

Linux

### Version

4.5.0

### Relevant log output

```shell
karavan   | 2024-04-26 19:53:33,019 ERROR [org.apa.cam.kar.api.DevModeResource] (executor-thread-30) java.lang.NullPointerException: Cannot invoke "org.apache.camel.karavan.model.DockerComposeService.getPortsMap()" because "dcs" is null
```

**Comment by mgubaidullin** [comment]
There was no Karavan 4.5.1 release

**Comment by jva70** [comment]
A link from https://github.com/apache/camel-karavan/blob/main/docs/WEB_DOCKER.md to [docker-compose.yaml](https://github.com/apache/camel-karavan/blob/main/docs/install/karavan-docker/docker-compose.yaml) points to a file that contains `image: ghcr.io/apache/camel-karavan:4.5.1`. 

Sorry if I considered to be a valid release ID.
