### ISSUE TITLE
All Beans are gone after integration is edited through yaml editor

### ISSUE THREAD

**Issue by dpalinic** [apache/camel-karavan#1280]
### Describe the bug

All Beans are gone after integration is edited through yaml editor just after beans are created. Video recording is attached.

https://github.com/apache/camel-karavan/assets/801314/e068dbd9-e300-4dfa-bf1d-70c79a2f6fee

### Steps to reproduce the behavior

1. Create an integration
2. Go to Beans and define any bean
3. Immediately after that, click on YAML tab and change anything in the code manually (e.g. id or something)
4. Observer all defined Beans are removed from Beans tab

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.4.0

**Comment by mgubaidullin** [comment]
Have you tried 4.5.0 ?

**Comment by dpalinic** [comment]
No, I haven't pull next version yet.

**Comment by dpalinic** [comment]
Looks like the issue is fixed in version 4.5.1. Thanks
