### ISSUE TITLE
Add the possibility to change the maven repository used to build the images 

### ISSUE THREAD

**Issue by remiborredon** [apache/camel-karavan#1292]
### Describe the solution you'd like

Hello,

I'm beginning to use Camel Karavan (v4.6.0) but when I try to run a simple route with for example a paho client, I obtain that error:

> 
2024-05-22 12:44:58.649  INFO 15 --- [- MavenDownload] pache.http.impl.execchain.RetryExec : I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo1.maven.org:443: Network is unreachable

I know this is due to our security system and we have a server that can act as a mirror to point to maven repos. Unfortunatelly, I am not able to find how to configure  this in the documentation. Is it possible? If it is possible, I would suggest to add a line about this in the readme.

Thanks in advance for your help :-)

### Variant

Web Application

### Container Management (if applicable)

Docker

**Comment by mgubaidullin** [comment]
BTW. 4.6.0 is not yet released ;-)

**Comment by remiborredon** [comment]
Thanks a lot. That's weared, here is the beginning of my docker-compose file:

`name: karavan

services:

  karavan:
    container_name: karavan
    image: ghcr.io/apache/camel-karavan:4.6.0
    ports:
      - "8080:8080"
  `
I will go back to 4.5.1 then.

I must also provide credential to access the server, I suppose that I must use the variable "camel.jbang.mavenSettings" right?

**Comment by mgubaidullin** [comment]
The latest release was 4.5.0
You could find releases here https://github.com/apache/camel-karavan/releases

**Comment by remiborredon** [comment]
Thank you for the information.

Regarding my issue, I tried your solution but unfortunatelly, I saw that Camel still try to use the default repo. I saw in the doc that I shall use the settings.xml file to define a mirror using `camel.jbang.mavenSettings`.

I created a settings.xml file like this:

> <settings>
    <mirrors>
        <mirror>
	    <id>external-repository</id>
	    <url>https://myRepo/</url>
	    <mirrorOf>*</mirrorOf>
	    <name>Central mirror</name>
	    <username>MyUsername</username>
	    <password>MyPassword</password>
	   </mirror>
	</mirrors>
</settings>

I then mounted the file like this in my docker compose file:

>     volumes:
      - "./settings.xml:/var/settings.xml"

And I checked that the file is present at the good place.

Finally, I set ``camel.jbang.mavenSettings=/var/settings` and I built the image but unfortunatelly, I have the following error:

> 2024-05-22 15:27:20.733  INFO 15 --- [           main] org.apache.camel.main.MainSupport   : Apache Camel (JBang) 4.5.0 is starting
   2024-05-22 15:27:20.797  WARN 15 --- [           main] l.tooling.maven.MavenDownloaderImpl : Can't access /var/settings.xml. Skipping Maven settings.xml configuration.

And of course, my configuration is not taken into account. Do you know what I did wrong? Is there a special place for that file? The documentation speaks about ~/.m2 but the folder is not present in the image.

**Comment by mgubaidullin** [comment]
https://github.com/apache/camel-karavan/discussions/1226

**Comment by remiborredon** [comment]
Thank you for this link! I created a new docker image integrating my settings.xml file but it looks that the karavan.devmode.image field is not taken into account when set in the application.properties file of my project. Is it the correct place ? I was not able to find any reference to this field in the documentation.


Remi

BORREDON

Software Development Engineer MPU

**Comment by mgubaidullin** [comment]
`karavan.devmode.image` should be set for Karavan application itself, not for the project.
