### ISSUE TITLE
Outdated information about KARAVAN SERVERLESS MODE

### ISSUE THREAD

**Issue by manoger** [apache/camel-karavan#1298]
Hello 👋,

I hope you're doing well.

I noticed that the blog page [KARAVAN SERVERLESS MODE](https://camel.apache.org/blog/2021/11/camel-karavan-release-0.0.8/) contains incorrect commands in the "3. Install Karavan serverless" section. The instructions reference a karavan-demo folder that does not exist in the [apache/camel-karavan](https://github.com/apache/camel-karavan) repository.

To resolve this issue, I suggest updating the instructions with a git checkout to a specific commit where this folder and related commands are accurate. Alternatively, it might be better to delete this section if it no longer applies.

Thank you for addressing this.

Best regards

**Comment by mgubaidullin** [comment]
The blog page Posted on November 24, 2021
Till then a lot on things happened.
Karavan does not support Serverless mode and does not support Camel-K starting from 2022
