### ISSUE TITLE
Karavan capitalize the first letter of the ref

### ISSUE THREAD

**Issue by dzaow** [apache/camel-karavan#1301]
### Describe the solution you'd like

Karavan capitalizes the first letter of the ref value for a Process step.
Meanwhile sonnar recommends to keep names consistent:
https://rules.sonarsource.com/java/RSPEC-6830/

Is it possible to remove this forced capitalization?

### Variant

Vs Code Extension

### Container Management (if applicable)

None

**Comment by dzaow** [comment]
> I believe the java convention is to use PascalCase (Capitalizing the first letter), see page 20: https://www.oracle.com/technetwork/java/codeconventions-150003.pdf

Hello

1. The convention does not include the Spring Beans names description. But it has a description of variables and fields, which should be started with lowercase. (Check the page 16)
2. In the ref field I try to address the spring bean, which is, by convention, should be started with lowercase. https://docs.spring.io/spring-framework/reference/core/beans/definition.html#beans-beanname
3. The first letter can be capitalized for class name automatically during class creating.

**Comment by mgubaidullin** [comment]
Karavan focuses on camel-main runtime.
