### ISSUE TITLE
Upgrade Designer to Kamelets 4.7.0

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1340]
### Describe the solution you'd like

Upgrade Designer to Kamelets 4.7.0

### Variant

Web Application

### Container Management (if applicable)

None

**Comment by Anik-Bardhan** [comment]
Hello @mgubaidullin. Can this be assigned to me? I want to get familiar with how karavan works internally and working on this will help me understand it better.

**Comment by mgubaidullin** [comment]
Sorry @Anik-Bardhan but I need to unassign
Usually Kamelet upgrade is quite simple procedure, but this time Kamelet catalog comes with fasterxml.jackson version that is not compatible with the latest Vertx we use in generator. 
So we need to make an ugly workaround for generator this time.
