### ISSUE TITLE
Bug: Error createBuildScriptConfigmap: null

### ISSUE THREAD

**Issue by drblack666** [apache/camel-karavan#1351]
### Describe the bug

There is an error when running karavan in k8s - unable to create configMap. It seems `KARAVAN_ENVIRONMENT` can't be changed, is this behavior expected?
Running Karavan with `KARAVAN_ENVIRONMENT: dev` - works fine, but `KARAVAN_ENVIRONMENT: production` - gives an error.
What is this variable for? Can its value be changed?

### Steps to reproduce the behavior

* Set `KARAVAN_ENVIRONMENT` to something other than `dev` (e.g. `production`)
* Check logs for errors

### Variant

Web Application

### Container Management (if applicable)

Kubernetes

### Operating System (if applicable)

Linux

### Version

4.6.0

### Relevant log output

```shell
ERROR [org.apa.cam.kar.kub.KubernetesService] (executor-thread-1) Error createBuildScriptConfigmap: null
```

**Comment by mgubaidullin** [comment]
Karavan supports only `dev` value for KARAVAN_ENVIRONMENT variable.

**Comment by drblack666** [comment]
Maybe remove this variable and set it somewhere in the code? Or are there plans to implement other values?

**Comment by mgubaidullin** [comment]
I am pretty sure that it could work without KARAVAN_ENVIRONMENT variable.
We just need to clean up Kubernetes deployment resources
