### ISSUE TITLE
Bug: in build.sh jbang needs --runtime option

### ISSUE THREAD

**Issue by predic8** [apache/camel-karavan#1352]
### Describe the bug

Images build are failing. In build.sh the line:

`jbang -Dcamel.jbang.version=$CAMEL_VERSION camel@apache/camel export --local-kamelet-dir=$KAMELETS_DIR`

returns with:

`The runtime option must be specified`

Adding

--runtime=camel-main

fixes it.

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

Docker

### Operating System (if applicable)

MacOS

### Version

4.7.0

### Relevant log output

```shell
The runtime option must be specified
```

**Comment by davsclaus** [comment]
This is a bug in Camel 4.7.0 and has been fixed for 4.8.0. You can specifiy the runtime in `application.properties` which fails in 4.7.
