### ISSUE TITLE
Support Poll EIP

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1359]
### Describe the solution you'd like

Poll EIP is a new EIP added to Camel 4.8, that should have an icon. This EIP is a simpler version of PollEnrich so it can use the same icon possibly.

### Variant

Both

### Container Management (if applicable)

None

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
![poll-switch-animation](https://github.com/user-attachments/assets/3f8f1709-e425-4373-9f37-bb364e3fb891)
