### ISSUE TITLE
Topology Group Behaviour

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1362]
### Describe the solution you'd like

Topology shows Consumer/Producer groups if Switch active.
Otherwise Topology groups links between Consumer/Producer with similar URIs 

### Variant

Both

### Container Management (if applicable)

None

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
<img width="1317" alt="Screenshot 2024-08-16 at 1 17 51 PM" src="https://github.com/user-attachments/assets/ae8b1cdf-e659-4897-9c1a-93506e91bbaf">

<img width="1316" alt="Screenshot 2024-08-16 at 1 18 15 PM" src="https://github.com/user-attachments/assets/4fddffdd-8ce6-470c-a098-01e349f02931">

**Comment by predic8** [comment]
@mgubaidullin Thanks! Looks great.
