### ISSUE TITLE
Karavan to run in github for the web

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#137]
<img width="1453" alt="Screenshot 2021-12-01 at 09 39 46" src="https://user-images.githubusercontent.com/477100/144200568-ce696e3f-c6c7-404b-8562-1581a83a805b.png">

**Comment by davsclaus** [comment]
eg on github press the `dot` key which opens the web editor (VScode for web). And you can install extensions. But only some of them work for the web.

Maybe we can get karavan or some parts of karavan to work there.

**Comment by mgubaidullin** [comment]
Karavan works fine on GitHub Codespaces. github.dev aka click `dot` does not because of limitation required by Karavan
