### ISSUE TITLE
Add ability to create the integration projects created in Karavan as individul repository with ability to follow a branching strategy like Gitflow

### ISSUE THREAD

**Issue by kasiviswanathan13** [apache/camel-karavan#1370]
### Describe the solution you'd like

I recently started using Apache Camel Karavan and found it very useful and powerful, with ability to create integrations quickly, efficiently and that too a performant one. But I was having difficulty in managing the seperate projects as all of them were part of the same repo and they all share the same repo tree. One felt that it would be better if Karavan could initialize a new repo for each of the integrations created from within Karavan, say under a "git org" structure. Then we also need to give ability to pick branches on the designer / web UI when we work on an integration, so that some sort of branching merging strategy could be applied, like Gitflow.

### Variant

Web Application

### Container Management (if applicable)

Kubernetes

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
Apache Camel Karavan was specifically designed to simplify the development of integration microservices. Initially, Karavan supported multiple repositories to allow for separate project management. However, this approach made the project creation process cumbersome and time-consuming. It required creating separate repositories, generating and uploading keys, and configuring each repository in Karavan.

To streamline this process, Karavan now uses a single repository per instance. This change significantly reduces the complexity and time involved in project creation, allowing integrators to create and start implementing integration projects in just two clicks.
