### ISSUE TITLE
Issues When clicking build on Karavan .. Work's fine in Dev mode

### ISSUE THREAD

**Issue by woodarts** [apache/camel-karavan#1378]
### Describe the bug

When clicking build on Karavan have the following error, testopentelemetry is the name of the project

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"testopentelemetry-builder\" in pod \"testopentelemetry-builder\" is waiting to start: ContainerCreating","reason":"BadRequest","code":400}

Version I am using is 4.4.1

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.5.0

**Comment by mgubaidullin** [comment]
Does it work in 4.7.0?

**Comment by mgubaidullin** [comment]
no response
