### ISSUE TITLE
Ability to select git branch from the user interface

### ISSUE THREAD

**Issue by nickhristovta** [apache/camel-karavan#1382]
### Describe the solution you'd like

Currently the only way for a git branch to be selected is through the deployment parameters (`karavan.git-branch`). This does not provide a lot of flexibility - the only way to switch a branch is through a re-deployment of Karavan (or re-config / restart if working locally).

This feature may need to be extended to be actually quite a bit more complete (maybe entire repository management). Repository management is a much bigger ask, however, as it requires the storage and handling of secrets.

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
Apache Camel Karavan was specifically designed to simplify the development of integration microservices. Initially, Karavan supported multiple repositories to allow for separate project management. However, this approach made the project creation process cumbersome and time-consuming. It required creating separate repositories, generating and uploading keys, and configuring each repository in Karavan.

To streamline this process, Karavan now uses a single repository per instance. This change significantly reduces the complexity and time involved in project creation, allowing integrators to create and start implementing integration projects in just two clicks.
