### ISSUE TITLE
Karavan secret file how to add ssl_verify=False

### ISSUE THREAD

**Issue by tannextan** [apache/camel-karavan#1383]
### Describe the bug

I have added the git details inthe karavan secret in the kubernetes / openshift, the gitlab we have is using custom made ssl , so how to add the parameter ssl_verify=false 

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

Openshift

### Operating System (if applicable)

None

### Version

4.5.0

**Comment by mgubaidullin** [comment]
This is not a bug but a new feature

**Comment by tannextan** [comment]
Thanks , but i managed to solve that. Good will be if you can add the feature
