### ISSUE TITLE
Highlight Step in RED if Sensitive Field Contains Plain Value

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1388]
### Describe the solution you'd like

Highlight Step in RED if Sensitive Field Contains Plain Value

### Variant

Both

### Container Management (if applicable)

None

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
![sensitive](https://github.com/user-attachments/assets/9edd4878-6ccf-4874-80db-8c41ff154dfb)

**Comment by davsclaus** [comment]
1. should it be orange instead? its okay during prototyping and to get going.
2. maybe in the panel there should be a (* like) symbol as well (instead of * could be something else to indicate warn or hint).
