### ISSUE TITLE
[VS Code] White empty page

### ISSUE THREAD

**Issue by Croway** [apache/camel-karavan#139]
When using `Karavan: Create CRD`, `Karavan: Create YAML` or `Karavan: Open`, I get a white empty page, output logs are empty, where can I look for errors/logs?

![image](https://user-images.githubusercontent.com/34543311/144570134-825fa82e-20f0-4e7d-8acc-2b2734a14bbb.png)

**Comment by mgubaidullin** [comment]
@Croway what is your OS type and version, VSCode version and extensions installed?

**Comment by mgubaidullin** [comment]
You could find some logs in Developer Tool
<img width="194" alt="Screen Shot 2021-12-03 at 12 56 26 PM" src="https://user-images.githubusercontent.com/1379213/144650219-978e6305-a3b7-4032-8553-3f696ed0760d.png">

**Comment by Croway** [comment]
Fedora 35, vscode version: 1.62.3, karavan version 0.0.8 I think (from changelog)

![image](https://user-images.githubusercontent.com/34543311/144652237-c7096e6c-74b1-44a1-8a76-1bfd2519f4c3.png)

**Comment by mgubaidullin** [comment]
@Croway could you please try the latest build to check if it works. 
https://github.com/apache/camel-karavan/suites/5643164637/artifacts/184421617

**Comment by Croway** [comment]
Hi @mgubaidullin , latest build is working for me, thanks! 
![image](https://user-images.githubusercontent.com/34543311/158222736-960584b5-1052-48b1-b367-9859f097b428.png)

**Comment by mgubaidullin** [comment]
@Croway latest build of Karavan is based on the bleeding edge Camel 3.16.0 that is not yet released.
You could run your integration locally using Jbang
`jbang -Dcamel.jbang.version=3.16.0-SNAPSHOT camel@apache/camel run integration.yaml`

to run it on kubernetes/openshift you need to wait Camel-K version that is based on Camel 3.16+
