### ISSUE TITLE
 Support Git Authentication via Git Access Token instead of username/password

### ISSUE THREAD

**Issue by nploi** [apache/camel-karavan#1424]
### Describe the solution you'd like

Currently, Karavan-app only supports Git authentication with username/password, which is outdated and less secure. Please add support for:
- OAuth Tokens (Personal Access Tokens for GitHub, GitLab, Bitbucket, etc.)

This will improve security and align with modern Git providers' best practices.

### Variant

Web Application

### Container Management (if applicable)

Docker

### Operating System (for VS Code Extension)

None

**Comment by mgubaidullin** [comment]
GitHub Personal Access Tokens both Classic and Fine Grained could be set instead of password.
