### ISSUE TITLE
Enable route navigation to routes in other folders

### ISSUE THREAD

**Issue by cdia8890** [apache/camel-karavan#1439]
### Describe the solution you'd like

We would like to check the possibility of enabling navigation from one route to another (using the `Direct` component) when the called route is in another folder in the same root-level directory.

Currently, the UI navigation only works for routes in the same folder.

Expected:
```
/root-folder
├── /folder1
│   ├── main_route.camel.yaml (has a Direct component which calls sub_route.camel.yaml)
├── /folder2
│   ├── sub_route.camel.yaml
```
We're using this folder structure to improve the readability of our code base.

Highly appreciate it if you could check on the possibility of this.

Thanks!

### Variant

VS Code Extension

### Container Management (if applicable)

None

### Operating System (for VS Code Extension)

Windows

**Comment by mgubaidullin** [comment]
The flat folder structure in Karavan is an intentional design choice, ensuring that all xxx.camel.yaml files are located within a single directory.
