### ISSUE TITLE
When git service is outside of the cluster - UI cannot access it because of the timeout

### ISSUE THREAD

**Issue by arheom** [apache/camel-karavan#1444]
### Describe the bug

In our configuration we have a bitbucket outside of a kubernetes cluster. And to access it, it takes more than 5s, unfortunately. With the new updates of the UI inside the KaravanApi.tsx page, line:
axios.defaults.timeout = 5000;
it adds this timeout to all axios calls, including the one to git service. Because of that, Git pull / push inside the project fails.

It would be cool to be able to configure / disable the timeout, so it works also with git remote services which take longer than 5s to respond.

### Steps to reproduce the behavior

1. Configure a slower / remote git server
2. Navigate to a project
3. Pull
4. Timeout issue, from axios.

### Variant

Web Application

### Container Management (if applicable)

Kubernetes

### Operating System (if applicable)

None

### Version

4.8.0

**Comment by mgubaidullin** [comment]
In that case I would recommend to use Gitea installed in your kubernetes and configured to push to Bitbucket
https://docs.gitea.com/usage/repo-mirror#pushing-to-a-remote-repository

**Comment by arheom** [comment]
That would be a bit complicated, as all pipelines and such are based on the bitbucket. As I understood, the mirroring of gitea to bitbucket happens every once in a while. So, the developer flow somehow needs to wait for the sync to happen, before going to deploy to another environment from bitbucket / jenkins.
