### ISSUE TITLE
After update to 4.8.0 the Push button inside the project is disabled

### ISSUE THREAD

**Issue by arheom** [apache/camel-karavan#1445]
### Describe the bug

Updated from 4.6.0 to 4.8.0 (skipped the 4.7.0 as I had some hard issues to make it work) and noticed the Push button inside the project is disabled. I investigated why, and I have seen the condition:
isDisabled={!isDev || selectedFileNames.length === 0}

In debug mode, I have seen the isDev is false, but when I look at the api call to ui/ configuration, I get the following:
"environment": "dev",
    "environments": [
        "dev"
    ],

so, according to what I understand from ProjectStore.tsx, the isDev should be true.

Is isDev dependent on something else I might need to set, or is there any known issue with it? Any idea how I can forcely make it true?

### Steps to reproduce the behavior

1. Navigate to Projects -> Files
2. Push button is disabled

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.8.0

**Comment by mgubaidullin** [comment]
https://camel.apache.org/blog/2024/09/camel-karavan-4.8.0/#to-commit-or-not-to-commit
