### ISSUE TITLE
Run button doesn't work after VSCode upgrade to 1.63

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#148]
After upgrade VSCode from 1.62 to 1.63 `Run` button does not work anymore when Diargram (Webview) is opened.

For some reason arguments in `registerCommand` contains different `path` value, ex. `webview-panel/webview-XXXX` 
than `host` value of `new URL(window.location.href)`  in Webview itself.

In previous version of VSCode they was the same and we could match Button Click with the open WebView.

https://github.com/apache/camel-karavan/blob/0028aacfea847ea2a7f200faf42c85c43fdaf53c/karavan-vscode/src/extension.ts#L78 

https://github.com/apache/camel-karavan/blob/0028aacfea847ea2a7f200faf42c85c43fdaf53c/karavan-vscode/webview/App.tsx#L66

**Comment by apupier** [comment]
I guess that now there is a distinction between the `host` and the iframe `name`, by using developer tools and inspecting the webview, I found:
```
<iframe name="05d3cd2a-7b10-4f87-a944-7dfcd6db49df" class="webview ready" sandbox="allow-scripts allow-same-origin allow-forms allow-pointer-lock allow-downloads" allow="clipboard-read; clipboard-write;" src="vscode-webview://2853133e-9bb6-49d8-a6c0-788031a21ab6/index.html?id=2853133e-9bb6-49d8-a6c0-788031a21ab6&amp;swVersion=2&amp;extensionId=camel-karavan.karavan&amp;platform=electron&amp;vscode-resource-base-authority=vscode-resource.vscode-webview.net&amp;parentOrigin=vscode-file%3A%2F%2Fvscode-app" style="border: none; width: 100%; height: 100%;"></iframe>
```

I put log and the path provided to the command is now the iframe name.
