### ISSUE TITLE
Not working with VSCode on Windows

### ISSUE THREAD

**Issue by Premcnathan** [apache/camel-karavan#152]
With windows, I am facing below issue while saving the flow.

Error: ENOENT: no such file or directory, open 'C:\c:\Code\vscodeFolder\rrrd.yaml

Looks like the file path is not resolved properly in the extension for windows style.

**Comment by lucasortega** [comment]
Same problem. 

Issue described in https://github.com/apache/camel-karavan/issues/72

**Comment by Premcnathan** [comment]
Duplicate of #72. Hence closing!
