### ISSUE TITLE
Support multiple routes?

### ISSUE THREAD

**Issue by livespotty** [apache/camel-karavan#211]
I am trying to deploy the yaml generated by karavan that has multiple routes. I get the following error in the kubernetes pod.

ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.IllegalArgumentException: Unsupported field: steps

However there is no issue with single route defined. (ie., the yaml doesnt have "- route:" entry.

**Comment by davsclaus** [comment]
If you use latest karavan then its bleeding edge and needs Camel 3.15 or better 3.16 to run. Camel K is still using an older Camel 3.14.x release.

**Comment by toonalbers** [comment]
A temporary hack for anyone stuck with this issue could be https://gist.github.com/toonalbers/af217646745fa4706804c2f2c61c89e8

**Comment by mgubaidullin** [comment]
The hack ^^^ solves only route part. 
However REST DSL and bean reference has been changed as well.
So the best way is to help Camel Quarkus and Camel-K communities to upgrade asap

**Comment by livespotty** [comment]
By upgrading cluster to Nightly build solved this issue. 
Ref:https://github.com/apache/camel-k/releases/tag/1.9.0-nightly
