### ISSUE TITLE
Add jbang configuration for trace logging

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#216]
We can add a [x] in configuration to enable trace logging, so you can from the log output see the tracing of the message (until we get a better dashboard UI to visualize this)

Its the --trace option on the CLI.

**Comment by mgubaidullin** [comment]
What is the difference with `--logging-level=trace` that we already support?

**Comment by mgubaidullin** [comment]
<img width="548" alt="Screen Shot 2022-03-17 at 6 57 43 PM" src="https://user-images.githubusercontent.com/1379213/158907595-bf934749-3866-4250-84eb-c8e6fa104a44.png">

**Comment by davsclaus** [comment]
Ah yeah its message tracing, it outputs every step the message goes so you can see how the message is routed
