### ISSUE TITLE
Visual does not place outgoing and connections properly if underlying element is larger than view

### ISSUE THREAD

**Issue by cgballance** [apache/camel-karavan#226]
If there are many items stacked horizontally, let's say with a Choice element with a lot of When clauses, then the div will have a scrollable area. The outgoing elements will be pinned to the right edge of the viewable area, which is not right, cause it will obscure other elements to the right of any given outgoing.  The issue is that scrollHeight/scrollWidth should be used to properly
lay out the svg graphics.

**Comment by mgubaidullin** [comment]
Could you please provide the screenshot of the issue
