### ISSUE TITLE
[VSCode] JBang sends error when trying to launch an Integration with spaces in the file name

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#229]
When copying & pasting a file in VSCode the resulting file has a space in the name like `something copy.yaml` Karavan editor can open and work with the file, but when trying to run using JBang, the resulting command is not escaping the filename resulting in a failed launch.

**Comment by davsclaus** [comment]
Ah yeah I guess we need to put the file name in quotes - also that should work on both mac/linus/windows, so I guess it may have to double quotes?
