### ISSUE TITLE
[vs-code] Integrate with VS Code AtlasMap

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#231]
several scenarii in mind:
- when a data transformation exists, clicking on it is opening the Atlasmap editor and allows editing it
- when adding a data transformation, ask for the name/path(?) then open the AtlasMap editor

using VS Code AtlasMap commands to open files named .adm will work (done by VS Code language Support and VS Code Designer for Camel)

Advantages: can leverage existing VS Code AtlasMap and should simplfiy integration compared to have Karavan embedding AtlasMap
Drawback: this will be specific to VS Code

**Comment by lhkg1988** [comment]
wait in hope

**Comment by mgubaidullin** [comment]
Due to AtlasMap limitations and lack of project further development we are not going to integrate with AtlasMap.
We are brainstorming and prototyping first-class citizen solution designed for Camel
