### ISSUE TITLE
kamelets in developer mode - Have some kind of scrap pad with brokerURL configs for quick reuse

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#233]
When using kamelets then you need to type in the brokerURL, username, port etc every time.

I wonder if we can make some kind of way in karavan that can popup with a list of same config used elsewhere, so you can quickly select one and have it auto inserted values.

We can consider some kind of metadata in the camel-catalog that can link X options together as a group, so karavan can use this to know which are grouped together to build up that list of "used elsewhere".

**Comment by davsclaus** [comment]
In the postman example, then you have same settings for the kafka broker, and postgres database etc.

**Comment by mgubaidullin** [comment]
![copy-paste](https://user-images.githubusercontent.com/1379213/160320531-51d8cc60-91bf-4d67-8a71-14edb89b1c15.gif)

**Comment by davsclaus** [comment]
Oh that is really good
