### ISSUE TITLE
Integrations panel - Make it easier to show yaml source

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#246]
The new integrations panel is lovely, and when you open yaml integrations, then the visual UI is shown.
However you may want to see the generated yaml source (or be able to edit in yaml and update UI) but its not as easy to open the yaml source.

You have to go back to folder panel, and open the file there.
<img width="2136" alt="Screenshot 2022-03-29 at 07 27 13" src="https://user-images.githubusercontent.com/477100/160539924-b5731929-da96-4cab-9ff2-a76f0e975d4b.png">

**Comment by mgubaidullin** [comment]
Something like that?

<img width="462" alt="Screen Shot 2022-03-29 at 11 01 01 AM" src="https://user-images.githubusercontent.com/1379213/160642080-d54cec44-50f6-45dd-8da9-592ec2255721.png">

**Comment by davsclaus** [comment]
yeah that is great
