### ISSUE TITLE
EIPs with required options seems not to indicate this

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#251]
The ref option is required on process eip
https://github.com/apache/camel/blob/main/core/camel-core-model/src/generated/resources/org/apache/camel/model/process.json#L15

However when I remove the value (making it blank) then karavan does not indicate its a required option.
Maybe it should highligh this in the panel. And also show that in the tooltip.

<img width="1344" alt="Screenshot 2022-03-29 at 17 35 02" src="https://user-images.githubusercontent.com/477100/160649665-2389d9e9-a3ef-4c77-ac70-bb7b8a9fa952.png">

**Comment by mgubaidullin** [comment]
Indicator and tooltip added.
verification will be implemented later
