### ISSUE TITLE
karavan-core missing cross-env in package.json

### ISSUE THREAD

**Issue by cgballance** [apache/camel-karavan#291]
The test stanza is missing cross-env prior to environment variable set and npm execution

**Comment by mgubaidullin** [comment]
1. I got `sh: cross-env: command not found` error
2. Looks like project cross-env is "finished" by it's author https://github.com/kentcdodds/cross-env/issues/257

**Comment by cgballance** [comment]
npm install -g cross-env
# you must be on a new vm or ???
It's being used in karavan-vscode's package.json too, so it is consistent.

i don't know of an alternative unless you want to get rid of it from vscode's package.json too.
It has been in karavan-vscode's package.json since original commit.

**Comment by cgballance** [comment]
needed for a build on windows(native shell).

**Comment by mgubaidullin** [comment]
In that case it should be in devDependencies

**Comment by cgballance** [comment]
good catch, i'll get that in, using the same version as in vscode
