### ISSUE TITLE
openapi example

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#293]
We should see if we can build something similar to Brunos blog post
https://quarkus.io/blog/camel-quarkus-effortless-apis/

This requires that we get the openapi maven plugin integrated with camel-jbang or something so karavan can use, or that we run the tool as part of running camel-jbang, meaning that karavan can "know this in advance".

Karvan can then have a wizard to import the openapi json spec file, and then you can design the Camel routes what should happen when these rest endpoints are invoked.

To run the app then camel-jbang can automatic load the same openapi json spec file, and based on that generate the needed camel route snippets that link the openapi spec to the camel routes via the direct:xxx naming pattern.

**Comment by mgubaidullin** [comment]
Is there a way to call maven command from JBang without installing maven on a machine? Or we need to create specially JBang staff?

**Comment by davsclaus** [comment]
We can start making the example - we have the generate rest command in jbang now. 

In the near future we can potentially add a flag to camel run, so you can use --openapi to refer to the spec file, and then we call the generate goal automatic as part of the run action.

**Comment by davsclaus** [comment]
https://github.com/apache/camel-karavan/tree/main/karavan-demo/openapi

There is an generate rest command now
