### ISSUE TITLE
Broken layout after resize when left panel was taking the whole place

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#294]
in some cases, the resize of the window ends up with a broken layout:
![brokenLayout](https://user-images.githubusercontent.com/1105127/162433691-b879844c-072c-45e6-b9bb-0ef040e1aeff.gif)

**Comment by mgubaidullin** [comment]
Karavan RouteDesigner UI re-draw connection arrows on window resize event.
But [Patternfly Drawer](https://www.patternfly.org/v4/components/drawer) component (that makes Properties panel resizable) has lots of responsive staff build in that executes after window resize.

To be honest, I don't know how to fix that either than make Properties panel fixed width.
