### ISSUE TITLE
Missing parameters on Kafka Component as a source

### ISSUE THREAD

**Issue by rstroop** [apache/camel-karavan#300]
sslTruststoreLocation and sslTruststorePassword are both required for me to make a secure connection using the Kafka Component. When I use the component as a source they show up, but when I use the component as a sink they do not. I can add them manually to the CRD and they are not deleted, but I believe they should be under the security settings in the UI.

**Comment by mgubaidullin** [comment]
Karavan generated from Camel-catalog, so required https://issues.apache.org/jira/browse/CAMEL-17937 to be fixed first

**Comment by mgubaidullin** [comment]
https://issues.apache.org/jira/browse/CAMEL-17937 is fixed and parameters are generated
