### ISSUE TITLE
Unsupported field: steps

### ISSUE THREAD

**Issue by guterresrafael** [apache/camel-karavan#302]
Integrations don't work when running "apply" on camel-karavan (serveless mode)
What config is missing for camel-k to use yaml?

([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application[39m[38;5;203m: java.lang.IllegalArgumentException: Unsupported field: steps
at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248)

**Comment by davsclaus** [comment]
Are you running this on Camel K, then Karavan requires Camel K 1.9.x release (not released yet).

**Comment by davsclaus** [comment]
See also: https://github.com/apache/camel-karavan/issues/198
