### ISSUE TITLE
Kamelets seems missing in 0.0.14 vscode

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#304]
When I create a new route (CRD) then I can only select source from components, and not kamelets.
<img width="1838" alt="try1" src="https://user-images.githubusercontent.com/477100/162907833-e3906ab1-c9dc-43d6-b3e9-00c9887b281f.png">
<img width="2036" alt="try2" src="https://user-images.githubusercontent.com/477100/162907859-63ffa11d-620f-46ab-8268-b1746e087dbf.png">

**Comment by mgubaidullin** [comment]
@davsclaus I could not reproduce your issue.
Could you please reinstall it and clean `~/.vscode/extensions/camel-karavan.karavan-0.0.14`

**Comment by davsclaus** [comment]
Thanks I just tried that but its still the same for me. I may try to reinstall vscode and clean that entire .vscode folder.

**Comment by apupier** [comment]
@davsclaus have you tried to close VS Code after uninstalling? Just "reloading" is not clearing some cache folders, especially `~/.vscode/extensions/camel-karavan.karavan-0.0.14`
