### ISSUE TITLE
EIP icons in VSCode dark mode are not very visible in the wizard selector

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#305]
0.0.14

When I want to add an EIP then the wizard shows me the EIPs. The EIP icon before the EIP name is black, and its hard to see, for example the Choice icon in the red circle:

<img width="1552" alt="Screenshot 2022-04-12 at 09 46 58" src="https://user-images.githubusercontent.com/477100/162908618-0d0051d4-e0a0-4b50-a6e6-98b342941f09.png">
.

**Comment by mgubaidullin** [comment]
Agree. But it requires a lot of work to make svg-base64 icons to react-svg components to be able to manage colours.
Eventually we will fix it.

**Comment by mgubaidullin** [comment]
<img width="1174" alt="Screen Shot 2022-04-12 at 10 59 38 AM" src="https://user-images.githubusercontent.com/1379213/162992419-84ecc643-e97b-4aa5-b8c7-c06e8c475b17.png">

**Comment by davsclaus** [comment]
Awesome that looks really good
