### ISSUE TITLE
Component list - Versions displayed seems wrong

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#306]
The version such as 3.16.0, and 3.14.0 in the components list. I assume it was intended as _first version_ when the component was added to Camel, like we do in the website.

In karavan then these versions seems to be 3.16.0, 3.16.0-SNAPSHOT and then some with 3.14.0.

If so then these versions are wrong, for example camel-ahc has firstVersion 

    "firstVersion": "2.8.0",

<img width="1525" alt="Screenshot 2022-04-12 at 14 09 14" src="https://user-images.githubusercontent.com/477100/162959615-15a018a2-a864-45ab-93f1-f0a61bc2f8d6.png">

**Comment by mgubaidullin** [comment]
This is the version of component that was used to generate Karavan.
Karavan Generator should remove old files before generate
