### ISSUE TITLE
vscode replicating components in new route dialog

### ISSUE THREAD

**Issue by cgballance** [apache/camel-karavan#310]
opened a yaml file in native vscode editor, then clicked on karavan to see the graphical view.
open new route shows kamelets+components(so far so good).  If i click on the raw yaml in the tabs, then
back over to the graphical view.  This time all components/kamelets are replications(2 of each).  Going back and forth between the tabs(raw and graphical) results in more and more copies being created in the dialog.

**Comment by mgubaidullin** [comment]
@cgballance could you please try the latest build? it should be already fixed

**Comment by cgballance** [comment]
tried latest, still an issue.  did some research on this.  
karavan-vscode/webview/App.tsx::onMessage will get called with a message.command of 'kamelets' or 'components' or others(unimportant for this issue). They will call KameletApi.saveKamelets(...) or ComponentApi.saveComponents(...) over in karavan-core.
These methods will do a push onto the respective arrays, thereby just piling on if the events are triggered.  There are similar methods for single additions that appear to be in non-vscode.
honestly, i'd rename these methods to something more understandable.  I'd have
ComponentApi.setComponents(...)  meaning set to the provided array.
ComponentApi.addComponent(...) meaning append to the existing array.

**Comment by mgubaidullin** [comment]
The second parameter indicated that array should be cleared before adding new values

![Screen Shot 2022-04-12 at 3 46 21 PM](https://user-images.githubusercontent.com/1379213/163041828-ec6325bb-5f13-4110-bd52-4a03f00d417a.png)

**Comment by cgballance** [comment]
somehow my local didn't update. sorry for the sideshow.

**Comment by cgballance** [comment]
My files don't have the param.  It's not on the main branch, just looked.
