### ISSUE TITLE
User should be able to create Kamelet

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#315]

**Comment by mgubaidullin** [comment]
What are the limitations for YAML DSL in Kamelet compare to Integration?
As far as I understand Kamelet should have to: "kamelet:sink" as the last step. 
Only one from in flows.
Anything else?

**Comment by Premcnathan** [comment]
Hi,

I have created a kamelet in java DSL like below. I am looking for a way through which I can show it in Karavan UI.  Just wanted to check if this issue is created for the same requirement. Thanks in advance!! 

```
routeTemplate("mykamelet").
           templateParameter("message", "customMessage").
            from("kamelet:source").
                      //do something
                to("kamelet:sink");
```

CC: @bvahdat

**Comment by mgubaidullin** [comment]
Kamylets should be created in YAML DSL and published to the Catalog.
Custom Kamelets could also be saved in custom Kamelet folder (for VS Code see Settings) or custom Kamelet repository (see karavan-cloud/openshift/katavan-secrets.yaml)

**Comment by mgubaidullin** [comment]
User should be able to select component parameters and create kamelet properties for them

**Comment by durgapmenon** [comment]
One query. 

Suppose, I create an Integration Route from Karavan and refactor the yaml file it into a custom kamelet based on a custom-kamelet example uploaded by Claus in GitHub. 

Is it possible to bundle up this custom kamelet having a  supporting Java Bean class and make it appear still in Karavan's Kamelet library?

I'm just curious to know if Karavan only picks up ***.kamelet.yaml files directly from the custom-kamelet folder configured in VS Code. 

It would be a bit more structured if separate folders are present for each custom Kamelet also having custom business logic in the Java Bean class/component.
