### ISSUE TITLE
Install Jbang automatically

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#316]
currently, it requires that JBang is available on command line.

**Comment by mgubaidullin** [comment]
Any tips how to make it?

**Comment by apupier** [comment]
Some examples of VS Code extensions downloading binaries automatically:
- VS Code Kubernetes https://github.com/vscode-kubernetes-tools/vscode-kubernetes-tools/blob/master/src/components/installer/installer.ts
- VS Code Camel K (not a very good example but the one I know the most). https://github.com/camel-tooling/vscode-camelk/blob/main/src/installer.ts
- VS Code OpenShift connector

**Comment by mgubaidullin** [comment]
Thanks @apupier
