### ISSUE TITLE
Create a NPM package

### ISSUE THREAD

**Issue by assimbly** [apache/camel-karavan#321]
To easily embed Karavan into a (Javascript) webapplication (Front-ends like plain JS, Electron, React, Vue or Angular) it would be nice if Karavan is available as npm package (https://www.npmjs.com).

**Comment by guoxunbo** [comment]
Yes. I alse had this requirement. 
It will be very nice if Karavan is available as npm package. 
Looking forward for it very much.

**Comment by sagar22091998** [comment]
@assimbly @guoxunbo did you guys find any solution for this?
