### ISSUE TITLE
VSCode URI not being formed correctly for JT400 component

### ISSUE THREAD

**Issue by ThePrez** [apache/camel-karavan#326]
Trying to create a new route from the VSCode plugin. As I type the object path, it seems to repeat the whole string in from the "object path" field with every keystroke. For instance, the following is from selecting MSGQ type then typing `/qsys.lib/qusrsys.lib/jgorzins.msgq`
>jt400:://MSGQ//q/qs/qsy/qsys/qsys./qsys.l/qsys.li/qsys.lib/qsys.lib//qsys.lib/q/qsys.lib/qu/qsys.lib/qus/qsys.lib/qusr/qsys.lib/qusrs/qsys.lib/qusrsy/qsys.lib/qusrsys/qsys.lib/qusrsys./qsys.lib/qusrsys.l/qsys.lib/qusrsys.li/qsys.lib/qusrsys.lib/qsys.lib/qusrsys.lib//qsys.lib/qusrsys.lib/j/qsys.lib/qusrsys.lib/jg/qsys.lib/qusrsys.lib/jgo/qsys.lib/qusrsys.lib/jgor/qsys.lib/qusrsys.lib/jgorz/qsys.lib/qusrsys.lib/jgorzi/qsys.lib/qusrsys.lib/jgorzin/qsys.lib/qusrsys.lib/jgorzins/qsys.lib/qusrsys.lib/jgorzins./qsys.lib/qusrsys.lib/jgorzins.m/qsys.lib/qusrsys.lib/jgorzins.ms/qsys.lib/qusrsys.lib/jgorzins.msq/qsys.lib/qusrsys.lib/jgorzins.ms/qsys.lib/qusrsys.lib/jgorzins.msg/qsys.lib/qusrsys.lib/jgorzins.msgq

Any advice on how I can gather useful data?

**Comment by mgubaidullin** [comment]
To fix after https://issues.apache.org/jira/browse/CAMEL-18015
