### ISSUE TITLE
Can Karavan be also used to create routes for a traditional Camel application?

### ISSUE THREAD

**Issue by msbober** [apache/camel-karavan#347]
Hi,

Can Karavan editor be also used to create routes for a traditional Camel application, e.g. a Spring Boot Camel application, as opposed to a Camel-K services?

I would like to use the editor to create the routes that would be dynamically loaded to a running Camel context.

Thanks!

**Comment by davsclaus** [comment]
We may add in the future make Karavan support editing other DSLs such as XML.
However here in the beginning we focus on one DSL which is YAML.

**Comment by davsclaus** [comment]
See the routes configuration example at
https://github.com/apache/camel-spring-boot-examples/tree/main/routes-configuration

It shows another feature in Camel (route configuration) but it has a mix of DSLs also yaml
