### ISSUE TITLE
Local setup

### ISSUE THREAD

**Issue by Viswaprya** [apache/camel-karavan#365]
Hi I am trying to do the local setup of the camel-karavan code in my laptop by following the readme
cd  karavan-vscode/yarn run compile getting failed with below error

ERROR in ./src/builderView.ts 22:0-88
Module not found: Error: Can't resolve 'karavan-core/lib/model/ProjectModel' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/extension.ts 24:0-44 51:26-37

ERROR in ./src/builderView.ts 23:0-71
Module not found: Error: Can't resolve 'karavan-core/lib/api/ProjectModelApi' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/extension.ts 24:0-44 51:26-37

ERROR in ./src/commands.ts 21:0-79
Module not found: Error: Can't resolve 'karavan-core/lib/api/CamelDefinitionYaml' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/designerView.ts 21:0-39 86:24-46 91:16-38
 @ ./src/extension.ts 20:0-46 39:23-35

ERROR in ./src/designerView.ts 22:0-79
Module not found: Error: Can't resolve 'karavan-core/lib/api/CamelDefinitionYaml' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/extension.ts 20:0-46 39:23-35

ERROR in ./src/designerView.ts 23:0-75
Module not found: Error: Can't resolve 'karavan-core/lib/model/IntegrationDefinition' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/extension.ts 20:0-46 39:23-35

ERROR in ./src/integrationView.ts 22:0-79
Module not found: Error: Can't resolve 'karavan-core/lib/api/CamelDefinitionYaml' in 'D:\camel-karavan-main\karavan-vscode\src'
 @ ./src/extension.ts 21:0-52 40:30-45 ..........

**Comment by mgubaidullin** [comment]
you neen to install karavan-core first by doing `npm install` in karavan-core folder

**Comment by Viswaprya** [comment]
After npm install inside karavan-core folder, lib folder is generated but still the error exists. Not sure what I am missing.

![karavan-issue](https://user-images.githubusercontent.com/25364795/173635454-744854c7-fa2e-4443-b60d-e1a5b71e6da5.JPG)

**Comment by mgubaidullin** [comment]
I usually open karavan-vscode in vscode and use `npm run package` or `npm run watch`
it copies required karavan-designer files
