### ISSUE TITLE
Karavan: JBang Run command is not working when called from palette 

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#373]
![Screenshot from 2022-06-17 15-19-12](https://user-images.githubusercontent.com/1105127/174306160-dba32104-5aba-46b5-8f1b-7043239c1e84.png)

tried both with the file opened in Karavan editor and yaml editor

**Comment by mgubaidullin** [comment]
Is it still the case?

**Comment by apupier** [comment]
yes

**Comment by mgubaidullin** [comment]
What is you OS ?

**Comment by apupier** [comment]
Fedora 6

**Comment by davsclaus** [comment]
closing old ticket
