### ISSUE TITLE
[VS Code Server] Long time to load Karavan UI

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#374]
Locally, on my destop it is taking few seconds.
On internal instance of Red Hat OpenShift Dev Spaces, it is taking more than a minute. (would be nice to test in GitHub Codespaces to compare)

I profiled it with Chrome Devtools, profile file is available to Red Hatters only: https://drive.google.com/file/d/1n2tk6Vmx0pNv0gJYAG_cA3X4Q1BIINok/view?usp=sharing

**Comment by mgubaidullin** [comment]
fixed in upcoming 3.18.5
