### ISSUE TITLE
Name of a Custom bean endpoint

### ISSUE THREAD

**Issue by ninjahail** [apache/camel-karavan#398]
I am using bean endpoint to add custom beans that i have created. I have used 4 bean steps, in the flow all the step comes with name "BEAN". Is there any way we can change the name of the bean?

**Comment by ninjahail** [comment]
![Uploading karavan flow screenshot.PNG…]()

**Comment by mgubaidullin** [comment]
Screenshot is not available

**Comment by mgubaidullin** [comment]
is it still a problem?
