### ISSUE TITLE
DoTry and DoCatch not working

### ISSUE THREAD

**Issue by ninjahail** [apache/camel-karavan#401]
I am trying to catch a JsonValidation exception from JsonValidatior action kamelet using try catch. But the catch block is not catching the exception.
this is the flow yaml:
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: helix-json-flow.yaml
spec:
  flows:
    - route:
        from:
          uri: kamelet:timer-source
          steps:
            - doTry:
                steps:
                  - to:
                      uri: kamelet:json-schema-validator-action
                      parameters:
                        template: file:jsonschema.json
                doCatch:
                  - steps:
                      - log:
                          message: '''error received:  Not Valid'''
            - bean:
                ref: com.infosys.platforms.StepsDemo.transform.transform
                beanType: com.infosys.platforms.StepsDemo.transform.transform
                method: process
            - to:
                uri: mongodb:mongo
                parameters:
                  collection: JsonFiles
                  database: Helix
                  hosts: localhost:27017
                  operation: insert
                  outputType: Document
            - log:
                message: '''received body: ${body}'''
                loggingLevel: INFO
          parameters:
            period: 300000000
            message: >-
              { "BreweryCod" : "MERR01", "InterfaceRunTimeStamp":
              "09-03-2021-06:35:19", "ArrivalTSP" : "09-03-2021 06:35:19",
              "CustomerNumber" : "50001", "LoadTenderID" : "80023" }

**Comment by davsclaus** [comment]
Its a bug in camel itself, will be fixed in 3.18.1 and newer releases.
