### ISSUE TITLE
Improve REST Path property for Path Params

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#408]
When creating a rest method you can use `{something}` to indicate a path param. There is no way in the Path field to configure this and notice the existence of path params.

**Comment by mgubaidullin** [comment]
@hguerrero could you please elaborate/add screenshots ? I dont understand the problem

**Comment by mgubaidullin** [comment]
@davsclaus could we add more information to REST models in catalogue?

**Comment by davsclaus** [comment]
Yes the description in the model can be updated, then when you click that `?` icon then it shows that.

Anyone is welcome to help write a better description we can use
https://github.com/apache/camel/blob/main/core/camel-core-model/src/main/java/org/apache/camel/model/rest/RestDefinition.java#L104

**Comment by mgubaidullin** [comment]
Captions come from Camel itself and if requires should be fixed there
