### ISSUE TITLE
[VS Code]Add an option to generate only routes from an OpenAPI

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#414]
**Environment**
- Karavan version: 0.0.15 
- Platform:  Mac

**Current behavior**
Currently options are generate REST Only or REST and Routes

**Expected/desired behavior**
Add an option to generate only routes

**Minimal reproduction of the problem with instructions**
Generate a simple OpenAPI, right click on it.

* Others:
This is because we want to pass the openapi file to the execution of the routes from a service registry, so that is always getting the latest version, no need to update the details of the rest configuration.

**Comment by mgubaidullin** [comment]
If your openapi was changed you need to generate rest dsl.
In what case you need only routes without rest dsl?
