### ISSUE TITLE
Tekton-pipelines

### ISSUE THREAD

**Issue by SujalaTangudu** [apache/camel-karavan#425]
How to clone or get contents of a file from AZURE DEVOPS repository in TEKTON_PIPELINES ?

**Comment by mgubaidullin** [comment]
I beleive that Azure DevOps repo is a Git repo, so it should work in Tekton Pipelines if you configure Karavan secrets properly at https://github.com/apache/camel-karavan/blob/main/karavan-builder/openshift/karavan-secret.yaml
