### ISSUE TITLE
Missing Set Property (EIP) in vs code extension

### ISSUE THREAD

**Issue by Jasmin-Sk** [apache/camel-karavan#426]
In karavan vs code extension when I am trying to add setProperty (which is EIP) in route it is not showing up in the list.

**Comment by mgubaidullin** [comment]
Already added. It will be available in the next release
https://github.com/apache/camel-karavan/blob/2131158bd635fd1c6e20782a6132e6abaa7835ef/karavan-designer/src/designer/utils/CamelUi.tsx#L55
