### ISSUE TITLE
Why delete denpendencies?

### ISSUE THREAD

**Issue by lhkg1988** [apache/camel-karavan#456]
visual studio code extend has denpendencies.

**Comment by mgubaidullin** [comment]
Now Karavan uses application.properties to manage dependencies ex. https://github.com/apache/camel-karavan/blob/782487168237f0abf3aa151dfd1afda627aafbca/karavan-demo/postman/project/application.properties#L7

1. camel-jbang knows how to use it
2. when you export project into cael-quarkus, spring-boot or camel-main dependensies will be exported accordingly
