### ISSUE TITLE
camel-jbang configuration consulting

### ISSUE THREAD

**Issue by suoxun** [apache/camel-karavan#457]
I want to know more about the configuration and meaning of camel-jbang in application.properties, as shown below:
![image](https://user-images.githubusercontent.com/48100625/184810681-60adabc1-4638-4174-9a51-2ceeaf2c2317.png)
I have found the official document address（https://camel.apache.org/manual/camel-jbang.html）, but the configuration instructions above are few. I would like to find some more complete and detailed configuration instructions. Do you have the document address here?

**Comment by davsclaus** [comment]
These are internal options for camel-jbang and karavan that is used when running Camel and exporting to quarkus or spring-boot.

**Comment by davsclaus** [comment]
@mgubaidullin maybe the options that are karavan only, eg `project-id` ... should be using `camel.karavan.xxx` as keys?

**Comment by mgubaidullin** [comment]
Agree. Lets make it like this in 3.19
