### ISSUE TITLE
How to enable karavan for HTTPS?

### ISSUE THREAD

**Issue by ninjahail** [apache/camel-karavan#461]

**Comment by mgubaidullin** [comment]
@ninjahail could you please elaborate? HTTPS for Karavan App, HTTP component, etc?

**Comment by ninjahail** [comment]
For Karavan App .

**Comment by mgubaidullin** [comment]
Karavan app aimed to be deployed to Kubernetes/Openshift.
Current version works for OpenShift only (Kubernetes support coming soon): https://github.com/apache/camel-karavan/tree/main/karavan-builder/openshift

How to configure HTTPS on OpsnShift: https://docs.openshift.com/container-platform/4.10/networking/routes/secured-routes.html
