### ISSUE TITLE
Dependencies is missing

### ISSUE THREAD

**Issue by MorganaPrado** [apache/camel-karavan#463]
after the version update the dependencies disappeared and broke the whole project
<img width="840" alt="dep" src="https://user-images.githubusercontent.com/26443242/185675693-47210ba3-0d79-4e2b-a31a-4d2e44750883.PNG">

**Comment by mgubaidullin** [comment]
To sync dependency management in camel runtimes, now they are in `application.properties`

How to generate default `application.properties`

![karavan-vscode-depenencies](https://user-images.githubusercontent.com/1379213/185701985-099585b7-a435-4c97-8ed9-809dbab4cd08.gif)

**Comment by MorganaPrado** [comment]
But what do I do with the resources I'm using in the route without the dependencies tab
![image](https://user-images.githubusercontent.com/26443242/186207267-c6721525-1a75-4d8b-aeea-943ac4e0fe22.png)

**Comment by mgubaidullin** [comment]
you can add your dependencies in `application.properties` file in `camel.jbang.dependencies` line

**Comment by MorganaPrado** [comment]
in this case I will add mvn:classpath:RemoveSoapEnv.xslt for example?

**Comment by mgubaidullin** [comment]
I think that dependencies should be java libs in maven repository
For classpath resources you should use `camel.jbang.classpathFiles` property

**Comment by MorganaPrado** [comment]
So I tried to do as you said, but I still have the dependency error, do you have example?
![image](https://user-images.githubusercontent.com/26443242/186729927-81b3c198-ef58-474b-973f-5e669c54d725.png)

**Comment by mgubaidullin** [comment]
@davsclaus what is correct properties for the files in classpath fro camel-jbang?

**Comment by davsclaus** [comment]
If the xslt files are local, then they should likely be using `file:xxx` instead of `classpath:xxx` or even without any scheme, eg just `xxx`.

**Comment by davsclaus** [comment]
However I think Karavan should have a nice UI for configuring dependencies (a bit like we had before) but then it stores it automatic in that properties file for you.

**Comment by MorganaPrado** [comment]
I've already tried to put only the path or just the name of the file and even then it doesn't recognize it, before with the dependency tab it worked just fine

**Comment by mgubaidullin** [comment]
@MorganaPrado what is your runtime: camel-jbang, quarkus, camel-k? version?
