### ISSUE TITLE
parameter mapping problem

### ISSUE THREAD

**Issue by suoxun** [apache/camel-karavan#466]
I want to define kafka's consumption output parameters to map to the following http input parameters, as shown below:
![image](https://user-images.githubusercontent.com/48100625/186062803-26bdcb1f-cae3-4aaf-935d-fde335995c94.png)
The question now is:
1. There is no parameter setting for the component definition on the interface.
2. AtlasMap can only fill in uri, and there is no interface to flexibly configure parameter mapping.

**Comment by mgubaidullin** [comment]
Component parameters are generated from Camel catalogue metadata.
If some of them missing, please provide their names.


![xxx](https://user-images.githubusercontent.com/1379213/190517174-a3f71440-e2a8-4d52-95aa-88b0e9310e38.gif)
