### ISSUE TITLE
RouteConfigurationId property issue

### ISSUE THREAD

**Issue by gopikiran079** [apache/camel-karavan#471]
When configured Route Configuration Id for a route, it is getting stored with key **routeConfigurationId** instead of **route-configuration-id**  and due to this build getting failed.

Even when manually changed, it is getting automatically replaced

**Comment by mgubaidullin** [comment]
What runtime do you use? camel-jbang, camel-quarkus, camel-k? version?
Canonical way for camel is camelCase YAML.

**Comment by anil-perikala** [comment]
We using camel-quarkus

**Comment by mgubaidullin** [comment]
Looks like an issue with camel-yaml-dsl.
I have opened a ticket https://issues.apache.org/jira/browse/CAMEL-18433

**Comment by anil-perikala** [comment]
if we replace routeConfigurationId manually to route-configuraion-id, then it is running fine

**Comment by mgubaidullin** [comment]
kebab-case is the old version of YAML DSL, camelCase is the new version. 
Karavan is based on the new DSL. 
Camel is still supporting both, but there is a bug (https://issues.apache.org/jira/browse/CAMEL-18433)

**Comment by anil-perikala** [comment]
ohh.. ok .. thanks for the clarification

**Comment by mgubaidullin** [comment]
https://issues.apache.org/jira/browse/CAMEL-18433 is fixed so it should work with camel 3.18.2
