### ISSUE TITLE
Access control and configuration not working.

### ISSUE THREAD

**Issue by abhi-ar17** [apache/camel-karavan#476]
I have deployed Karavan in Kubernetes , I am able to open Karavan and create new project but while clicking on access control and configuration tabs getting only white screen. Is the access control feature not yet available? Or do I have to do any other changes to get those.
![image](https://user-images.githubusercontent.com/47202835/190142901-7b699b99-8a3e-4153-ad45-c098fdb6e63d.png)

**Comment by mgubaidullin** [comment]
Access control and configuration pages are not  implemented.

Access control won't be implemented. Instead we add SSO/Keycloak integration in the next release.
