### ISSUE TITLE
Beans properties should hide sensitive options

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#478]
If the key are part of the sensitive names then we should hide it with this "password" thingy, eg where you can click that "eye" icon to show it.

<img width="1821" alt="Screenshot 2022-09-20 at 08 38 41" src="https://user-images.githubusercontent.com/477100/191185468-f06b17e8-b7f1-4e5d-b3a8-d322d6546780.png">

**Comment by mgubaidullin** [comment]
Where to get this kind information? Do we have catalog of beans? It would be great!

**Comment by davsclaus** [comment]
This class has the list
https://github.com/apache/camel/blob/main/core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java

We do not have it in a .json file or something, unless you walk through all components and their properties and check for secret = true

**Comment by davsclaus** [comment]
In Camel 3.19 you can now find a json file array with all the sensitive key names
https://issues.apache.org/jira/browse/CAMEL-18534

**Comment by mgubaidullin** [comment]
Done
