### ISSUE TITLE
Exception and Error handling implementation process

### ISSUE THREAD

**Issue by Asraf-Uddin-Ahmed** [apache/camel-karavan#481]
I want to implement the following Java part of `exception` and `error` handling to Karavan.

```java
errorHandler(deadLetterChannel("file:./deadmessage?fileExist=Append")
      .maximumRedeliveries(3)
      .redeliveryDelay(2000)
      .onPrepareFailureRef("failureProcessor"));

onException(Exception.class)
      .handled(true)
      .to("slack:#{{slack.channel}}")
      .to("stream:out");
```
I have no clue how to implement it. Can anyone help me?

**Java Version: 11
Camel Version: 3.18.2
Karavan Version: 3.18.2**

**Comment by davsclaus** [comment]
There is a TODO to add UI in Karavan for error handling. Its complex.

You can edit the yaml file directly and add what you need to do, you can find inspiration from some of the unit tests in camel-yaml-dsl, such as
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/OnExceptionTest.groovy


And there is also a bit of doc here
https://camel.apache.org/components/3.18.x/others/yaml-dsl.html
