### ISSUE TITLE
Camel components that are not remote should be illustrated as local only

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#484]
When using some components that are local, direct/seda and others like message transformers like velocity, xj etc then they are not calling a remote server.

But in karavan then the UI shows that there is a "external call" - I wonder if we need to define per component if its a local or remote call, then tooling can know this and illustrate this in the UI accordingly.

Some components that can be both, eg file, we woul
<img width="1573" alt="Screenshot 2022-09-26 at 15 33 44" src="https://user-images.githubusercontent.com/477100/192290921-48ae1e42-c27f-46d7-bd8b-9f6374146dc5.png">
d assume its remote, eg to store to a "file".

**Comment by davsclaus** [comment]
The screenshot above is using the XJ component to transform from XML to JSon - this is a local process only, so it would be nice to not have that -----------------> cloud icon.

**Comment by davsclaus** [comment]
Here is how it would look like if using XJ as a kamelet instead (action)
<img width="1556" alt="Screenshot 2022-09-26 at 15 38 40" src="https://user-images.githubusercontent.com/477100/192291328-289fdd8d-c769-4f7c-a68b-ee755bf0424f.png">

**Comment by mgubaidullin** [comment]
For Kamalets it is quite clear source are incoming, sink are outgoing, actions are internal calls,
How to define for components?

**Comment by davsclaus** [comment]
yes you are correct - for components then we need to have some way to annotate that so we can generate that information in the json file that camel-catalog / karavan can use to know.

**Comment by davsclaus** [comment]
I created a ticket in camel
https://issues.apache.org/jira/browse/CAMEL-18559
