### ISSUE TITLE
Filtering the component / kamelet dialog should update counter

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#489]
When filtering then the counter (123 and 308) should update with how many matches the filter.

For example typing xml then there is 9 components and 2 kamelets. So it would be good if the counters is updated so you quickly can see this.

<img width="1221" alt="Screenshot 2022-10-15 at 23 28 28" src="https://user-images.githubusercontent.com/477100/196008257-5dc2ddc2-5600-4918-a7f4-dfdad0c4bccc.png">

**Comment by mgubaidullin** [comment]
Fixed https://github.com/apache/camel-karavan/pull/517
