### ISSUE TITLE
Blank white screen displayed

### ISSUE THREAD

**Issue by anandasastry** [apache/camel-karavan#498]
I have installed Karavan extension in Visual Studio code. I tried to create a Karavan Integration using the command pallette. I am getting a blank white screen displayed instead of the UI

**Comment by mgubaidullin** [comment]
1. Whats is your Karavan version?
2. What Operating system you use?
3. Could you please attach screenshot/s of your problem?
4. Do you have any Error messages?
5. Could you please open View/Command palette/Developer: Toggle Developer Tools  and copy error messages?

**Comment by notesronin** [comment]
Same issue:
Karavan 3.18.4
macOS 13.0 / Apple M1 Pro
Visual Studio Code 1.17.2

<img width="625" alt="Screenshot 2022-10-28 at 13 30 04" src="https://user-images.githubusercontent.com/8729057/198578028-2ef12cd0-ca61-4566-971a-cbf5f746baae.png">

No error message

Dev tools console:


console.ts:137 [Extension Host] openKaravanWebView
webview.js:2 message.command activate
20
Failed to decode downloaded font: <URL>
20
OTS parsing error: invalid sfntVersion: 1702391919
webview.js:2 message.command kamelets
webview.js:2 message.command components
webview.js:2 message.command showStartHelp
webview.js:2 message.command open
webview.js:2 saveScheduledChanges true
webview.js:2 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Wl (webview.js:2:188336)
    at webview.js:2:136917
    at Lo (webview.js:2:148496)
    at Us (webview.js:2:192919)
    at _l (webview.js:2:179771)
    at Dl (webview.js:2:179699)
    at Cl (webview.js:2:179562)
    at gl (webview.js:2:176549)
    at webview.js:2:126370
    at t.unstable_runWithPriority (webview.js:2:211571)
webview.js:2 Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Wl (webview.js:2:188336)
    at webview.js:2:136917
    at Lo (webview.js:2:148496)
    at Us (webview.js:2:192919)
    at _l (webview.js:2:179771)
    at Dl (webview.js:2:179699)
    at Cl (webview.js:2:179562)
    at gl (webview.js:2:176549)
    at webview.js:2:126370
    at t.unstable_runWithPriority (webview.js:2:211571)

**Comment by notesronin** [comment]
Done. I forgot to specify that the blank screen issue happens when on the "Welcome to Karavan" dialog selecting the  Get started button. (Extension 3.18.4)

The extension 3.18.5 does not present that dialog, and yes I can edit a route as it was already possible in 3.18.4
 
<img width="932" alt="Screenshot 2022-10-28 at 15 33 47" src="https://user-images.githubusercontent.com/8729057/198614797-926f46ce-d768-4fb3-8d8e-a91eceeba597.png">

**Comment by mgubaidullin** [comment]
Thanks for your feedback. Yes, this tour was quite buggy. We removed it for now.
