### ISSUE TITLE
Improve documentation to install Karavan-app on minikube

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#502]
I have followed the exact steps documented to install on [Minikube](https://github.com/apache/camel-karavan/blob/main/karavan-cloud/MINIKUBE.md), but the steps needed some updates.

**Comment by davsclaus** [comment]
Are you able to help update the documentation? For example send a PR with doc updates?

**Comment by mrinalsharma** [comment]
Yes, that's my goal. I would like to start contributing to the project

**Comment by mrinalsharma** [comment]
The latest update by @mgubaidulli has fixed minikube deployment steps.  I have verified that the deployment is successful by following the [steps ](https://github.com/apache/camel-karavan/blob/main/karavan-cloud/MINIKUBE.md).  I think some documentation about [karavan-operator](https://github.com/apache/camel-karavan/tree/main/karavan-operator) will be helpful.

**Comment by mrinalsharma** [comment]
Minikube deployment is successful.
