### ISSUE TITLE
How to configure Auto Startup in a route using Env variable?

### ISSUE THREAD

**Issue by DiegoBetancourtC** [apache/camel-karavan#511]
In my Java DSL, I have something like this:

```
 from("direct:my-route").autoStartup("{{env:MY_ENV_VAR_ONE:false}}")
           .process(new Processor() {
            ...
```

Which gives the option to start the route based on the value of the env variable `MY_ENV_VAR_ONE`.

I have tried Karavan but it only provides the option to turn on or off the Auto Startup property of the route, but no more. Is it possible to use env variables with this property?

--

I'm using Karavan in Visual Studio Code version v3.18.4 - Mac OS X

**Comment by davsclaus** [comment]
The yaml DSL is in some areas more basic in this area and offer boolean, int, types that otherwise in Java DSL is more rich and allow to use property placeholders for many options.

**Comment by davsclaus** [comment]
We would need to enrich the camel-yaml-dsl schema with information which options can have a string property placeholder as well (or check via camel-catalog) and then Karavan can have some kind of "..." button to set the option via a placeholder syntax

**Comment by mgubaidullin** [comment]
@davsclaus any progress on enriching camel-yaml-dsl schema with information which options can have a string property placeholder?

**Comment by davsclaus** [comment]
Yes @mgubaidullin you can find out via camel-catalog model files, eg

In camelYamlDsl.json you have

```
      "org.apache.camel.model.RouteDefinition" : {
        "type" : "object",
        "properties" : {
          "autoStartup" : {
            "type" : "boolean"
          },
```

Then you can find out its an option on `org.apache.camel.model.RouteDefinition`, which you can find in camel-catalog and match by `javaType` as in `route.json` snippet below:

```
{
  "model": {
    "kind": "model",
    "name": "route",
    "title": "Route",
    "description": "A Camel route",
    "deprecated": false,
    "label": "configuration",
    "javaType": "org.apache.camel.model.RouteDefinition",
```

Then you have the correct model class, and inside its properties you can find

```
    "autoStartup": { "kind": "attribute", "displayName": "Auto Startup", "required": false, "type": "string", "javaType": "java.lang.String", "deprecated": false, "autowired": false, "secret": false, "defaultValue": "true", "description": "Whether to auto start this route" },
```

And see that the type is `string`. And therefore it supports what the user reported.

I assume you use this kind of "indirection" anyway to find documentation (eg = description) for every EIP option. So karavan must have some code that captures this, and then you can use it to find out which options can also be a "string" where you can use property placeholders, env variables and so on.

This can also happens for options that are numeric (not only for boolean)

**Comment by mgubaidullin** [comment]
@davsclaus are placeholders (properties or ENV VARs) supported for every parameters that are type=string in catalog?

**Comment by davsclaus** [comment]
> @davsclaus are placeholders (properties or ENV VARs) supported for every parameters that are type=string in catalog?

Yes they are

**Comment by mgubaidullin** [comment]
After https://github.com/apache/camel-karavan/issues/836

**Comment by mgubaidullin** [comment]
@davsclaus I have found only 4 fields in RouteConfiguration that are defined as `boolean` in camelYamlDsl.json and as `string` in camel-catalog.
