### ISSUE TITLE
Karavan pipelines running on Private registry

### ISSUE THREAD

**Issue by amiralopez** [apache/camel-karavan#512]
Is there an easy way to use a private registry such as gcr.io?. I noticed that the quarkus-builder-script-kubernetes.sh has some of the variables hardcoded such as username=sa & insecure=true. Does it expect to be running a local registry (using Minikube for instance) or is there a way to authenticate to a private repo at the moment? Thanks!.

**Comment by mgubaidullin** [comment]
We are planning to add private repositories in the future.

As for today, you could simply change pipeline to add authentication. 
It won't be overwritten because Karavan Operator creates PipelineTask only if it does not exists

**Comment by amiralopez** [comment]
Thanks for the quick response!.

> We are planning to add private repositories in the future.
> 
> As for today, you could simply change pipeline to add authentication. It won't be overwritten because Karavan Operator creates PipelineTask only if it does not exists

Thanks for the quick response!.

**Comment by mgubaidullin** [comment]
@amiralopez let's keep it open till it implemented
