### ISSUE TITLE
Integrated Experience for data mapping with XSLT

### ISSUE THREAD

**Issue by shuawest** [apache/camel-karavan#515]
Many traditional Integration and ESB technologies heavily used XSLT as the data mapping language and engine. While AtlasMap may be the target data mapping tool, but having some level of XSLT code highlighting and camel processor step integrated into the Karavan experience will help those moving from their prior experience, or drop into a more technical syntax for complex transformations that AltasMap doesn't support.

**Comment by davsclaus** [comment]
Mulesoft have their own transformation language
https://docs.mulesoft.com/dataweave/2.4/dataweave-language-guide

**Comment by mgubaidullin** [comment]
There is an extension for XSLT https://marketplace.visualstudio.com/items?itemName=deltaxml.xslt-xpath
So you could edit XSLT file using the extension and then use the file `to: "xslt:com/acme/mytransform.xsl"`
