### ISSUE TITLE
minikube -  Gitea Pipeline deploy cloning /kamelets issue [advise]

### ISSUE THREAD

**Issue by pocgit01** [apache/camel-karavan#518]
Environment: Minikube [following all deployment steps]
Gitea is deployed on a docker container and accessible from karavan 

I am able to commit pipeline to Gitea/Projects successfully, however when I Click Deploy I get the following error:

`step-karavan-build-deploy
Cloning into '/kamelets'...
fatal: Remote branch main not found in upstream origin
Cloning into '/scripts'...
warning: Could not find remote branch main to clone.
fatal: Remote branch main not found in upstream origin
/tekton/scripts/script-0-4xqh4: line 26: cd: /scripts/tttt1: No such file or directory
jbang -Dcamel.jbang.version=3.18.3 camel@apache/camel export --local-kamelet-dir=/kamelets
[jbang] Resolving dependencies...
[jbang]    org.apache.camel:camel-bom:3.18.3@pom
[jbang]    org.apache.camel:camel-jbang-core:3.18.3
[jbang]    org.apache.camel.kamelets:camel-kamelets:0.9.2
[jbang] Dependencies resolved
[jbang] Building jar...
The runtime option must be specified
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
[INFO] Processing build on daemon 4f5a940d
[INFO] Scanning for projects...
[INFO] BuildTimeEventSpy is registered.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.114 s
[INFO] Finished at: 2022-11-06T08:52:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/scripts). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException`

**Comment by mgubaidullin** [comment]
Karavan 4.0.0 does not use Tekton anymore
