### ISSUE TITLE
doTry and doCatch implementation 

### ISSUE THREAD

**Issue by manali-jambhale** [apache/camel-karavan#528]
in the previous issues it was mentioned that this will be implemented in the future release. It is completed or still work in progress?

**Comment by manali-jambhale** [comment]
I have installed the vs code extension for karavan. In the extension details it shows camel version 3.18.3 but still the try catch is not working. Please suggest if i am missing any step. How can i make it work on my end?
<img width="928" alt="vs-extn" src="https://user-images.githubusercontent.com/113964244/202363484-31dad5dc-8394-40f6-8c1c-5a70a5b6f73d.png">

**Comment by manali-jambhale** [comment]
Also the error handling and exception tab says "not implemented yet". Any idea on when would that be available?

**Comment by mgubaidullin** [comment]
What do you mean `try catch is not working`? Could you please provide detailed info:

**Environment**
- Karavan version: X.Y.Z 
- Platform:  

**Current behavior**


**Expected/desired behavior**


**Minimal reproduction of the problem with instructions**


* Others:

**Comment by davsclaus** [comment]
what runtime version of Camel do you use?
