### ISSUE TITLE
VS Code designer crashes when adding log-sink Kamelet

### ISSUE THREAD

**Issue by mikoskinen** [apache/camel-karavan#533]
**Problem:**

The Karavan VS Code designer goes all white when trying to add Kamelet log-sink. 

![karavan_crash](https://user-images.githubusercontent.com/143570/203708512-527d95c9-471b-4b74-bd06-ffa78cbb4ac0.gif)

**Other info:**

I wish I could provide more. I'm not seeing anything in the VS Code's Output view related to this.

**Karavan version:**

3.18.5

**VS Code version:**

Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

**OS version:**

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19043 N/A Build 19043

**Comment by mikoskinen** [comment]
Just tested this with Macbook (VS Code version 1.71.1) and encountered the same issue.

Log-sink doesn't seem to be the only one causing issues. If I:

1. Create new integration
2. Create new route
3. Add "Cuck Norris Source" (kamelet)

I get white designer. Nothing is saved into the file.

**Comment by mgubaidullin** [comment]
Duplicate https://github.com/apache/camel-karavan/issues/523
