### ISSUE TITLE
Add Fault Tolerance to Camel Status Collector

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#536]
https://github.com/apache/camel-karavan/blob/253b6090f6937d5272ed71518a12f27125b2df65/karavan-app/src/main/java/org/apache/camel/karavan/service/StatusService.java#L118

https://quarkus.io/guides/smallrye-fault-tolerance

**Comment by mgubaidullin** [comment]
@rafamqrs could you please take a look at this issue

**Comment by rafamqrs** [comment]
sounds good, I'm gonna take a look at it.
