### ISSUE TITLE
aws connectors giving s3 exception null

### ISSUE THREAD

**Issue by Jasmin-Sk** [apache/camel-karavan#538]
I have created route with kamelets aws s3 source, sqs source and given all required configuration its saying failed to start route because aws-s3-source-1 is null. Are aws connectors are working in karavan? Can i have any sample yaml with aws connectors.

**Comment by davsclaus** [comment]
you can find some aws examples at (that can run via jbang)
https://github.com/apache/camel-kamelets-examples/tree/main/jbang

Some of these examples may not use yaml DSL but show how to work with aws, that can help you
