### ISSUE TITLE
3.18.6 version not displaying Deployment/Pipelines/Pods status

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#539]
Is there a reason for commenting out line `//        startInformers();` in KaravanService.java

**Comment by mgubaidullin** [comment]
3.18.6 is not released yet and in active development now

**Comment by mgubaidullin** [comment]
https://github.com/apache/camel-karavan/releases

**Comment by mrinalsharma** [comment]
The work I am doing now to support the AWS cluster needs the latest code, that's why I raised the issue.  I guess I should have looked if it's released or not.

**Comment by mgubaidullin** [comment]
Sorry. I'll fix this today

**Comment by mgubaidullin** [comment]
Done.
I have simplified git integration https://github.com/apache/camel-karavan/issues/543

New configuration should be like: https://github.com/apache/camel-karavan/blob/7006e27c5449d5abd62521e0daa441c5b6ce73c0/karavan-app/src/main/resources/application.properties#L7
