### ISSUE TITLE
User should be able to deploy Karavan to an AWS Kubernetes cluster

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#540]

**Comment by mrinalsharma** [comment]
@mgubaidullin , Can you assign this ticket to me?

**Comment by mrinalsharma** [comment]
The current implementation makes use of .yaml files in karavan-cloud/AWS folder. Implementation depends on the creation of 1 cluster Node.

**Comment by mrinalsharma** [comment]
Should we close this issue and create a new one to support AWS installation via the operator?

**Comment by mgubaidullin** [comment]
Yes, please
