### ISSUE TITLE
Upgrade to quarkus 2.14.2

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#541]
There is a CVE in older 2.14.x release

**Comment by mgubaidullin** [comment]
1. Karavan Application is on Quarkus 2.13
2. Karavan uses 2.13 to generate project because of https://github.com/apache/camel-karavan/issues/542

**Comment by davsclaus** [comment]
quarkus 2.15.x is on the way so we are okay to stay on 3.18.x camel until we have 3.20 LTS next year
