### ISSUE TITLE
Kubernetes Config support

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#548]
Is there a way to override the properties in  `application.properties ` for karavan-app?  I would like to test with remote Infinispan server and need to update property `quarkus.infinispan-client.server-list` . If there is no way should we integrate [kubernetes Config](https://quarkus.io/guides/kubernetes-config)

**Comment by mgubaidullin** [comment]
You could overwrite application.properties with Environment variables
https://quarkus.io/guides/config-reference#environment-variables

**Comment by mrinalsharma** [comment]
Setting up an environment variable in `karavan-app-deployment-public.yaml` worked
