### ISSUE TITLE
Support Redis Cache

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#552]
There should be an option to select between Infinispan and Redis.

**Comment by mrinalsharma** [comment]
Do you envision Karavan being deployed at one place and managing (dev, test, qa, prod) from there? I think all these environments will have their own deployments of Karavan because, in a few organizations, Dev team doesn't have write permissions to Prod env.  Promoting code from one environment to another should be managed through Git repo.

Also limiting to just the use of Infinispan may be a gating issue for adoption as some organizations may only decide to use Redis or AWS SNS etc.

**Comment by mgubaidullin** [comment]
Karavan design by environments

![Screen Shot 2022-12-12 at 11 41 07 AM](https://user-images.githubusercontent.com/1379213/207102624-bda644b5-b279-44e4-af14-9f5f16957ebe.png)


![Screen Shot 2022-12-12 at 11 41 49 AM](https://user-images.githubusercontent.com/1379213/207102758-a07cb752-1523-4bb3-b5d9-62824fd5a0d5.png)

The main idea is to propagate not code but an immutable image between environments.

**Comment by mgubaidullin** [comment]
Companies that already adopted GitOps practices and has their own ArgoCD or similar products in place could replace the bottom part of deployment pipeline.

**Comment by mgubaidullin** [comment]
Karavan is toolkit for Integrator to help them create and deploy integrations. 

1. Changing technologies behind Karavan (react, Quarkus, Infinispan, etc) gives no values to Integrators
2. To support Redis and Infinspan we need to implements an abstraction layer between application and cache. Lot of work and no value for Integrators
3. To support Redis and Infinspan we need to implement Redis configuration support in Operator. Again lots of work with no value for Integrators.

**Comment by mrinalsharma** [comment]
You are right, Integrators don't care about react or Quarkus as the application is built using the language and container platform. I had the opinion to give the option to switch caching in case Infinispan is not a preferred caching solution for the company.  it's a component that stays outside of the app and not all the cloud providers give a managed option.

I think we can close this ticket for now and re-open it in the future if the need comes.
