### ISSUE TITLE
Goal of karavan-operator 

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#558]
why an operator was created when YAML files were doing the job and give more flexibility? Should the operator be updated to support AWS too?

**Comment by mgubaidullin** [comment]
1. To simplify installation process. Two files (karavan.yaml + karavan-secret.yaml) vs dozen files
2. To simplify upgrade process (when Karavan be mature enough to support upgrade) 
3. Next capabilities

<img width="1273" alt="Screen Shot 2022-12-12 at 1 00 06 PM" src="https://user-images.githubusercontent.com/1379213/207119570-0c098353-ec30-4ffe-9005-dc8928baf4c3.png">
