### ISSUE TITLE
Create a new Issue type where we can discuss code, implementation etc.

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#566]
It would be a good option to create a new Issue type like(Discussion, Feature request). That way we can have general discussions about features, code, etc, and not clutter unrelated tickets with a general discussion.

Thoughts?

**Comment by mgubaidullin** [comment]
As far as I know, we use Zulip chat for that. To be honest I'm not a big fan of Zulip chat.
I agree that it would be better if we could keep features, code, architecture discussion closer to the code/issues.

There is a Discussion feature in GitHub repository (Insights/Community tabs). 
It would be great if we could activate it.

@davsclaus is Zulip the only option for the community discussions or we could consider GitHub Discussion?

**Comment by davsclaus** [comment]
I have asked to enable GH discussions
https://issues.apache.org/jira/browse/INFRA-24021

**Comment by davsclaus** [comment]
> Discussions have been enabled, please verify that everything works as expected.

Can you guys check that it seems okay and working, then we can report back to INFRA

**Comment by mgubaidullin** [comment]
Looks like Discussions are activated.
Thanks @davsclaus
