### ISSUE TITLE
Operator should deploy Task and Pipelines if Tekton installed after Karavan

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#567]
1. Now Karavan operator deploys Tekton Tasks and Pipelines only Karavan Operator installed after Tekton Operator.
2. Karavan Operator should deploy Task and Pipelines if Tekton installed after Karavan
3. In Karavans tasks and pipelines are already in place Karavan Operator should **not** replace them, because users could customize pipleines for their needs

**Comment by dmvolod** [comment]
@mgubaidullin could you please assign this issue to me if possible.
It's not so clear to implement it right now after some discussions with OJSDK authors and brainstorming but seems to feasible with some hacks. Thanks in advance.
