### ISSUE TITLE
In the projects page, show if deployment is running for the project

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#575]
If the project list grows, user has to get into the project view to see the current status of Deployment. It would be good if the user can see the status in the project list. This way from the projects view, user can see which deployments are running/Stopped etc.
![image](https://user-images.githubusercontent.com/3838113/208985579-f3f2f846-5b77-4441-94ce-900483f3eae3.png)

**Comment by mgubaidullin** [comment]
I think it is already implemented by showing deployed project environment in Blue
https://github.com/apache/camel-karavan/blob/f11103082cda3bafae733eea428765ef1c0b9b55/karavan-app/src/main/webui/src/projects/ProjectsTableRow.tsx#L101

**Comment by mrinalsharma** [comment]
Yes, you are correct!! I have verified it.
