### ISSUE TITLE
Each DSL node should have generated ID

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#577]
DSL Node IDs are required for debugging

1. Route should have unique ID
2. First added routeConfiguration might have empty ID
3. Node IDs should be unique in each route route
4. User should be able to change generated IDs (System should check uniqueness for user defined IDs)
5. If open manually created YAML without IDs, system should generate IDs

**Comment by mgubaidullin** [comment]
@davsclaus could you please confirm ^^^ node IDs requirements for debugging

**Comment by davsclaus** [comment]
yes the BacklogDebugger uses nodeIDs

**Comment by cristph** [comment]
about this change  https://github.com/apache/camel-karavan/commit/2c1c1f6e58d8f3e11214852d94b71171904231e9
I'm wondering that it makes developer cannot change the already assigned id, it always keeps the old assigned value
if there's any concern?

```
karavan-designer/src/designer/route/property/DslPropertyField.tsx

    propertyChanged = (fieldId: string, value: string | number | boolean | any, newRoute?: RouteToCreate) => {
        if (fieldId === 'id' && CamelDefinitionApiExt.hasElementWithId(this.props.integration, value)) {
            value = this.props.value;
        }
        this.props.onChange?.call(this, fieldId, value, newRoute);
        this.setState({selectStatus: new Map<string, boolean>([[fieldId, false]])});
    }
```

**Comment by mgubaidullin** [comment]
Karavan automatically sets node IDs.
User can change node ID manually, however Karavan checks node ID uniqueness, because node ID should be unique in the route
