### ISSUE TITLE
Show default values in the option editor

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#58]
The default value for the period in the chuck norris kamelet is 10000
https://github.com/apache/camel-kamelets/blob/main/chuck-norris-source.kamelet.yaml#L24

It would be nice to see this value somewhere in the options editor (maybe in description, tooltip, or as a text below the input field.)
<img width="1625" alt="Screenshot 2021-10-31 at 09 17 39" src="https://user-images.githubusercontent.com/477100/139574276-4270c707-e87f-47d3-bb0d-4fac3b233c9a.png">

**Comment by mgubaidullin** [comment]
A text below textfiled makes UI noisy, so I have added to the Help tooltip


<img width="921" alt="Screen Shot 2021-11-01 at 11 06 35 AM" src="https://user-images.githubusercontent.com/1379213/139693886-a7c96118-59b7-48bc-bb58-e5e5a79ae0ed.png">
