### ISSUE TITLE
Support OAuth flow for components that support Grant Types(refresh-token, code)

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#580]
Support OAuth flow in Karavan-app with Grant Types(refresh-token, code) for components like  gmail, salesforce etc.

**Comment by mrinalsharma** [comment]
@mgubaidullin, Should this feature be supported?

**Comment by mgubaidullin** [comment]
This is a good food for thoughts ;-)
A lot of components require authentication and some of them are quite complex like OAuth 2.0
Aim of Karavan is to make Integration with Camel simpler for engineers
Also Karavan should provide opinionated solution

My vision that all authentication logic and token refreshes should be implemented in components themselves.
However we still need to store passwords/tokens/keys required and best-practice for that is to use Secrets and Key Vaults.

So, yes, this feature should be supported, but we need to define what part should be in Camel Framework, what part in Karavan and how to support secrets, vaults and keep same user experience in cloud application and vs code.

**Comment by mgubaidullin** [comment]
@davsclaus any thoughts on that ^^^ ?

**Comment by mgubaidullin** [comment]
Perhaps like camel-gmail component refreshToken?
https://camel.apache.org/components/2.x/google-mail-component.html
