### ISSUE TITLE
Unable to set Key in Caffeine Cache component in Visual Studio

### ISSUE THREAD

**Issue by joelicious** [apache/camel-karavan#598]
When configuring caffeine cache, the Key dialog has a "Select..." dialog box that then drops down to another "Select.." option.  This option is not selectable, leaving no options to set a Key (default Key).

The work around is to use a SetHeader before the Caffeine Cache invocation and specify the Key via setHeader.

Desired Behavior:  Would like to be able to specify the Key via the Key Dialog box.

**Comment by mgubaidullin** [comment]
Depends on https://issues.apache.org/jira/browse/CAMEL-18877

**Comment by mgubaidullin** [comment]
@joelicious could you please check if it is fixed.
