### ISSUE TITLE
Project should give an option to expose ports on Pod

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#600]
When a user creates an integration, there should be an option to add the ports that the pod can expose

**Comment by mgubaidullin** [comment]
In quarkus application you can do this by using `application.properties`

https://quarkus.io/guides/deploying-to-openshift
`quarkus.openshift.route.expose=true` for OpenShift

https://quarkus.io/guides/deploying-to-kubernetes
`quarkus.kubernetes.ingress.expose=true` for Kubernetes

**Comment by mrinalsharma** [comment]
Is it a supported feature or need to be supported?

**Comment by mgubaidullin** [comment]
It is already in place. Just add a dependency and property in application.property

**Comment by davsclaus** [comment]
If you have a TCP socket Camel route such as

from netty:0.0.0.0:1234

then you would need to be able to make a port mapping to expose 1234 in the container.
I am pretty sure both SB and Q has a way to configure this fairly easily with application.properties but it would be good to find out.

**Comment by mgubaidullin** [comment]
First you need to configure services for that
https://github.com/quarkusio/quarkus/blob/main/integration-tests/kubernetes/quarkus-standard-way/src/test/resources/kubernetes-with-multiple-ports.properties

**Comment by mrinalsharma** [comment]
> First you need to configure services for that https://github.com/quarkusio/quarkus/blob/main/integration-tests/kubernetes/quarkus-standard-way/src/test/resources/kubernetes-with-multiple-ports.properties

These properties mention HTTP, do they only work for HTTP?

**Comment by davsclaus** [comment]
yes its only for HTTP traffic, IMHO we also need a way to expose generic TCP ports like you do with docker ala -p 8080:8080

**Comment by mrinalsharma** [comment]
The following settings work to expose the port: We need to create a NodePort or Loadbalancer Service

![image](https://user-images.githubusercontent.com/3838113/212404462-49427742-f655-4bfa-8dc2-1ae8cca730a9.png)

**Comment by mrinalsharma** [comment]
Examples in https://github.com/apache/camel-karavan/pull/608
