### ISSUE TITLE
Karavan-app should collect Camel statuses of external applications

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#605]
Karavan-app should collect Camel statuses of applications deployed outside Karavan.

Now Karavan Dashboard shows external Camel Applications by getting all deployments with 'app.openshift.io/runtime=camel` or `app.kubernetes.io/runtime=camel' labels. However Quarkus and Spring Boot applications have different health URLs, so Karavan does not know which one to use. We need to define somehow, ex. through additional label

**Comment by mrinalsharma** [comment]
How will be the information on external applications used by users within Karavan app?

**Comment by mgubaidullin** [comment]
External apps: apps build and deploy by Karavan VS Code extension or any other camel-quarks or camel-spring-boot apps.

Karavan app will show them on Dashboard page: deployment status, service, pod, camel health.

It's already partially working.

**Comment by davsclaus** [comment]
you can collect also some stats for a dashboard that you today can see via camel-jbang. So you can try to run jbang, and then execute `camel get` and some of the other commands to find interresting data that we can present in the dashboard.

**Comment by mgubaidullin** [comment]
This feature is to get and show camel context information from camel applications running in kubernetes alongside with karavan-app

**Comment by mrinalsharma** [comment]
Sure!! I am reviewing it. Will get back to you soon. When is the next release date?
    On Wednesday, April 5, 2023 at 09:01:43 AM EDT, Claus Ibsen ***@***.***> wrote:  
 
 


you can collect also some stats for a dashboard that you today can see via camel-jbang. So you can try to run jbang, and then execute camel get and some of the other commands to find interresting data that we can present in the dashboard.
