### ISSUE TITLE
Error during Generate Camel Models ad API for Typescript

### ISSUE THREAD

**Issue by Croway** [apache/camel-karavan#61]
I got this error during 
```
mvn clean compile exec:java -Dexec.mainClass="org.apache.camel.karavan.generator.KaravanGenerator" -f karavan-generator
```
seems like it is related to https://github.com/apache/camel-karavan/blob/main/karavan-generator/src/main/java/org/apache/camel/karavan/generator/CamelModelGenerator.java#L133, `"CamelApi.camelize.tx"` should be `"CamelAPI.camelize.tx"`

**Comment by mgubaidullin** [comment]
Thanks @Croway 
Sorry for what you see in the CamelModelGenerator class. It was done as the first experiment and randomly evolved with the project. I'm not proud of the code in it. Should be rewrite.
