### ISSUE TITLE
YAML-serialization options

### ISSUE THREAD

**Issue by operon-io** [apache/camel-karavan#618]
It would be nice to have options how to serialize the YAML-output from the visual-designer. At least:

- control how many new lines between adjacent routes. Now there's no spacing between routes, which make it look little cluttered.

- similarly control spacing between step-elements.

- where the "id", "description", and "autoStartup" -fields are placed (beginning or end of the route). Now it places at the end of the route, but I prefer placing them at the start of the route.

- to use multilines (e.g. in log-statements) or not, and after how many characters to break the line if the option is enabled. Now it uses the ">-" to break strings into multiple lines.

**Comment by operon-io** [comment]
Although your focus is in building the visual designer, I hope that you'll give some focus also for the source-format (YAML). There are probably many companies like ours where the text-format will be relevant for the foreseeable future: writing, editing, refactoring etc. is **much** faster with the text-format. Integrators most likely won't hop in using the visual designer as the main mode, so I bet your goal is unrealistic, but it is a really nice add-on for visualizing the routes and configuring components with the wizard whenever it makes sense.

**Comment by mgubaidullin** [comment]
@operon-io if you prefer YAML editing over visual, I would recommend [Language Support for Apache Camel extension](https://github.com/camel-tooling/camel-lsp-client-vscode) that supports Camel YAML DSL
