### ISSUE TITLE
Feature Request: Copy as New

### ISSUE THREAD

**Issue by joelicious** [apache/camel-karavan#622]
I have enjoyed the ability to copy and paste a Camel Step into another Camel Step.  For example, create a Log Step then copy a different Log Step into it.

Would like the ability to hit "copy" on a step and then paste as new step into a Route, without first creating an empty version of the step as a placeholder of sorts.

Current State: do leverage copy and paste, you need to create an empty Camel Step and then copy from another existing Camel Step.

Expected State: Be able to hit copy on a Camel Step, and then, in some form, perhaps via the add arrow or ?, just hit paste and the step is added to a route.

**Comment by mgubaidullin** [comment]
@joelicious could you please check
