### ISSUE TITLE
VS Code Plugin: Blue camel icon on top right corner to switch from YAML to Visual design not available

### ISSUE THREAD

**Issue by rlpcgft** [apache/camel-karavan#641]
Hi, I have just updated the VS Code Karavan plugin to its latest version 3.20 and the blue Camel icon that was allowing me to open the visual designer directly from the YAML source code is not available anymore.

Thank you

**Comment by mgubaidullin** [comment]
It was replaced by MagicWand icon from standard palette to follow VS Code UI style.

**Comment by mgubaidullin** [comment]
I think MagicWand better describes what Karavan does 😉

**Comment by rlpcgft** [comment]
Hehe it does indeed... :)

...but I don't see it either... at least not in the same place. Is it supposed to be elsewhere??

I haven't changed anything else, just updated the plugin version in the VS Code Extension section. (and restarted a couple of times to double check). 

The YAML is being recognized as Camel Route since at least at the very top is showing the tooltip "Camel Debug with JBang"

When I go back to the previous version of the plugin, everything is fine

Thank you for your help!

**Comment by rlpcgft** [comment]
Ah no worries I found it.

It now needs the extension *.camel.yaml

right?

**Comment by mgubaidullin** [comment]
Yes, you need to use *.camel.yaml extension

**Comment by rlpcgft** [comment]
ok thank you!
