### ISSUE TITLE
Update to Camel 3.20.2

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#642]
https://camel.apache.org/blog/2023/02/RELEASE-3.20.2/

**Comment by mgubaidullin** [comment]
@davsclaus how it will work with camel-quarkus where we still have 3.20.1 ?

**Comment by davsclaus** [comment]
CEQ will run with the Camel version that CEQ was released with. You cannot change Camel version :(
Its not as free as Spring Boot

**Comment by kumarinstor** [comment]
@mgubaidullin  we are using this apache caravan library for one my business use case , when I try to run karavan-app to add few custom kamalets, am getting some errors, is there any way I can schedule a call and discuss with you on this issues, please suggest
