### ISSUE TITLE
Integration with Git Webhooks

### ISSUE THREAD

**Issue by rstroop** [apache/camel-karavan#645]
I know right now Karavan doesn't pull from git, but I know that is a planned feature. Once that is implemented it would be nice to have webhook integration such that git would tell the deployment about the update and trigger a pipeline run even if I am not in the UI to watch it.

**Comment by mgubaidullin** [comment]
Depends on https://github.com/apache/camel-karavan/issues/647

**Comment by mgubaidullin** [comment]
I think we better use camel-git instead of webhooks
https://camel.apache.org/components/3.20.x/git-component.html

**Comment by rstroop** [comment]
The benefit of using git webhooks is you can subscribe to the events from github: https://docs.github.com/en/webhooks-and-events/webhooks/about-webhooks

This means you don't have to poll for changes all the time, and instead react to an event.

**Comment by mgubaidullin** [comment]
1. karavan is not tight to github ;-)
2. if karavan service in unavailable we loose event

**Comment by rstroop** [comment]
I was hoping it would be a service that runs in openshift and triggers the karavan pipeline when an event happens. So I don't have to log in just to press the button in karavan or openshfit. Come to think of it, the pipeline is probably where the hook should be set up. As part of the karavan UI, I'm fine with having to hit a button to refresh or "pull" changes that might have been made to the repository after I last pushed.
