### ISSUE TITLE
Ability to Select Pipeline to run

### ISSUE THREAD

**Issue by rstroop** [apache/camel-karavan#646]
We will eventually have the need to run different pipelines for different types of workloads. Currently you can edit the pipeline that karavan runs to make changes, but being able to select a different pipeline entirely would be helpful for more flexibility.

**Comment by rstroop** [comment]
From the Karavan UI in OpenShift I want to be able to select from a list of "OpenShift Pipelines" to run. Currently two pipelines are created, one for SpringBoot and one for Quarkus. A pipeline is selected based on what runtime was chosen at the creation of the project. If you want to make changes to the pipeline you can, but then all projects have to use that change. In a larger development environment, I would rather be able to create a custom pipeline that could be selected per project.

**Comment by mgubaidullin** [comment]
It should also work for Kubernetes with Tekton. Not only Openshift

**Comment by mgubaidullin** [comment]
It should also work for Karavan VS Code developed projects with https://github.com/apache/camel-karavan/issues/645

**Comment by mgubaidullin** [comment]
1. Remove pipeline deployment from Operator
2. Pipeline should be in git repository in special project `pipelines`
3. New property `camel.karavan.pipeline` in `application.properties` with default value  `karavan-pipeline-{ENVIRONMENT}-{RUNTIME}` ex: `karavan-pipeline-dev-quarkus`

**Comment by mgubaidullin** [comment]
Karavan 4+ does not use tekton
