### ISSUE TITLE
No option to create integration in vscode extension

### ISSUE THREAD

**Issue by Jasmin-Sk** [apache/camel-karavan#650]
In vscode extension there is no option to create new integration. Previously it used to have plus icon.

**Comment by mgubaidullin** [comment]
<img width="422" alt="Screenshot 2023-02-09 at 9 35 54 AM" src="https://user-images.githubusercontent.com/1379213/217842890-82206ce6-816f-4fdb-aba4-5a8350fafefd.png">

**Comment by mgubaidullin** [comment]
I got it. No button in Karavan view
