### ISSUE TITLE
User should be able to stop Pipeline 

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#662]

**Comment by mrinalsharma** [comment]
you can assign it to me.

**Comment by mgubaidullin** [comment]
I have only started to work on it a bit, but if you could do it I'm all in

**Comment by mgubaidullin** [comment]
I\m not sure if [this](https://github.com/apache/camel-karavan/commit/e94b9804f8ebedad1696a0de9235d65163b12a7e) works. Have not test it yet
