### ISSUE TITLE
Add operator E2E and integration tests

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-karavan#674]
It would be nice to have operator end-2-end and integration tests to validate at least basic reconcile logic.
Also complex Tekton deployment logic can be implemented with real operator build and deploy.

**Comment by mgubaidullin** [comment]
1. What do we need for integration test? Kubernetes environment?
2. I did not get the second. Care to elaborate

**Comment by dmvolod** [comment]
> * What do we need for integration test? Kubernetes environment?

Exactly. As OJSDK doesn't support Fabric8 Kubernetes Mock Server for tests, we need a real Kubernetes cluster for that. For example, we can utilize following github action for that. Also, would be nice to filter test running by folder change in commit, to reduce resources and skip operator tests if others Karavan components changed only.
https://github.com/marketplace/actions/kubernetes-kind-cluster

> * I did not get the second. Care to elaborate

Yes, sure. As #567 introduces Quarkus application restart hack, real Karavan operator deployment into the Kubernetes cluster should be done. Also, we need to deploy whole Tekton pipelines, or only CRD's part to reduce resource consumption, as we don't need to tests a whole integration flow for now.
What do you think about it?

**Comment by mgubaidullin** [comment]
`As https://github.com/apache/camel-karavan/issues/567 introduces Quarkus application restart hack` could you explain more?

**Comment by dmvolod** [comment]
Yes, sure.
Since, unlike the golang operator-sdk, OJSDK does not support dynamic event source inject and reloading, the only solution to get Tekton Pipelines and Tasks listeners after installing it is a complete reload of the entire operator Qaurkus application with sending exit code to it. 
In this case, standard integration tests with running operator locally inside the surefire plugin `operator.start()` will not work and we need to build and install operator bundle before running e2e tests and than just run tests against already deployed operator in the Kubernetes cluster.
