### ISSUE TITLE
Unable to run Karavan Designer locally

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-karavan#675]
Latest branch of the Camel Karavan (3.20.1-SNAPSHOT)
Probably missed something, but seems to `public/components/supported-components.json` is missing somehow.

Steps for reproduce:
- clear `camel-karavan` repository cloned from GitHub
- Generate Camel Models and API for Typescript (according to doc)
- npm install & npm start

Got following error on startup
```log
Proxy error: Could not proxy request /components/supported-components.json from localhost:3000 to http://localhost:8080/. 
```

Did not find, that some code is generating `supported-components.json` file

**Comment by mgubaidullin** [comment]
fixed https://github.com/apache/camel-karavan/commit/3f558f34d175bf588ef38a21fd3acb73681acfe0
