### ISSUE TITLE
Designer: direct-vm inbound route never create in wire-tap

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-karavan#680]
Probably, it's by design, but new `from(direct-vm...)` route never create, the same as for `direct` and `seda` components.

https://camel.apache.org/components/3.18.x/direct-vm-component.html
![image](https://user-images.githubusercontent.com/24249373/224335801-26b264f9-5e5b-4cfa-9ad7-f4d76adafec6.png)

UI asked for create, but it will be never done.

Sorry, @mgubaidullin for a lot number of bugs submitted.

**Comment by mgubaidullin** [comment]
1. [Direct-VM](https://camel.apache.org/components/3.18.x/direct-vm-component.html#) supports communication across CamelContext instances
2. [Multiple CamelContexts per application not supported](https://github.com/apache/camel/blob/main/docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc#multiple-camelcontexts-per-application-not-supported) starting from Camel 3

@davsclaus  Should not Direct-VM be deprecated according to this ^^^ ?

**Comment by davsclaus** [comment]
yes it should be removed in 4.x and deprecated in 3.21 onwards

**Comment by dmvolod** [comment]
Oh, thanks @davsclaus 
Closing issue in this case
