### ISSUE TITLE
Operator: Karavan CR strategy in the Kubernetes cluster (namespace)

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-karavan#681]
I don't really know is it by design or not, but now Karavan CR always create Deployment and other CRs with statically defined names "karavan" or simalar per namespace. Depends of the design, we should define:

- Validation web-hook which will block to create more than single Karavan CR per namespace
- If a single instance of Karavan deployment should be created per Kubernetes cluster, Karavan must be a cluster-wide CR
- If we will be allow to create as number of Karavan instances per namespace as possible, corresponding dependent resources name prefix should be constructed, instead of hard-coded values.

**Comment by mgubaidullin** [comment]
By design:
1. Only one Karavan deployment per namespace
2. Unlimited number of Karavan deployments per cluster
3. Deployment name `karavan` is hardcoded. 
4. User can not create project with name `karavan`

**Comment by dmvolod** [comment]
Ok, good point. Thanks for explanation.
In this case, validation web-hook which will block to create more than single Karavan CR per namespace should be created.

**Comment by mgubaidullin** [comment]
Karavan operator is deprecated in favour of installer
