### ISSUE TITLE
Proposal: Utilize Lombok for model POJOs

### ISSUE THREAD

**Issue by dmvolod** [apache/camel-karavan#689]
This is no-functional proposal, but can increase Java code maintainability and readability to reduce a large number of getters/setters/toString() etc. implementations which are too explicit.

https://projectlombok.org/

**Comment by dmvolod** [comment]
@mgubaidullin what do you think about this approach?

**Comment by davsclaus** [comment]
We do not use Lombok in any of the Apache Camel projects.

**Comment by dmvolod** [comment]
Ok, make sense. Thanks, @davsclaus . Closing issue
