### ISSUE TITLE
custom Kamelet not getting exported to classpath:/kamalet

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#709]
https://issues.apache.org/jira/browse/CAMEL-19255

**Comment by mrinalsharma** [comment]
@davsclaus  should this fix for [CAMEL-19255](https://issues.apache.org/jira/browse/CAMEL-19255) be backported to 3.20.2?

**Comment by davsclaus** [comment]
This is in camel-jbang that is in camel-core project, karavan will upgrade to 3.20.4 when its released later
