### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by andreufontb** [apache/camel-karavan#710]
It would be nice to have arm64 support in order to use on arm64 servers but also to be able to try it localy on arm computers like M1/2 macs or raspberry pi.

Regards,

**Comment by davsclaus** [comment]
i assume you talk about the karavan-cloud app that you can install in kubernetes ?

**Comment by andreufontb** [comment]
Yes, karavan-cloud to run in kubernetes.
Sorry for not being clear.

**Comment by mgubaidullin** [comment]
Works fine on Mac M2. Both Docker and Minikube
