### ISSUE TITLE
User "system:serviceaccount:karavan:pipeline" cannot create resource "rolebindings"

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#716]
Forbidden!Configured service account doesn't have access. Service account may have been revoked. rolebindings.rbac.authorization.k8s.io is forbidden: User "system:serviceaccount:karavan:pipeline" cannot create resource "rolebindings" in API group "rbac.authorization.k8s.io" in the namespace "karavan".

**Comment by mgubaidullin** [comment]
@dmvolod could you please take a look?

**Comment by mgubaidullin** [comment]
I have this error when start pipeline from Karavan application.
Looks like operator should set it during deployment

**Comment by dmvolod** [comment]
Probably yes, @mgubaidullin 
But I'm wonder why `deployer` Role should have a `rolebindings` create permissions. Need to be validated and tested with real Tekton deployment.

**Comment by mgubaidullin** [comment]
I made a demo today and faced this issue when deploy Camel application that uses configMaps and secrets
