### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by assimbly** [apache/camel-karavan#72]
After creating of a karavan yaml file in VSCode I get the following message:

Error: ENOENT: no such file or directory, open 'C:\c:\Users\me\Documents\workspace\test\test.yaml'

The file is editable, but doesn't seem to save (because of the double drive letter). After restart the yaml is gone.

OS: Windows 10 (Windows_NT x64 10.0.19043)
Version: 1.61.2 (user setup)
Commit: 6cba118ac49a1b88332f312a8f67186f7f3c1643
Date: 2021-10-19T14:57:20.575Z
Electron: 13.5.1
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0

**Comment by gallfra-bh** [comment]
Same problem as well for writing and reading operations with WIN 10 x64
Seems a problem with root folder
To test application and overcome issue I changed in the extension.js 
"karavan.open" and  open kankaravan.jbang-run  to use fsPath instead of path 
same approach for writing operation

**Comment by mgubaidullin** [comment]
Help needed in this case because I do not have Windows machine to reproduce.
I think it might be something in here https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L138

**Comment by gallfra-bh** [comment]
Yes, to save is something there at line 139
Here in the following in bold portion of code I made changes replacing path with  fsPath

var o = e.commands.registerCommand("karavan.open", (function () { for (var s = [], a = 0; a < arguments.length; a++)s[a] = arguments[a]; if (s && s.length > 0) { var o = t.readFileSync(r.resolve(s[0].**fsPath**)).toString("utf8"), u = r.basename(s[0]**.fsPath**), c = bn(u, o); c[0] ? En(n, i, u || "", c[1]) : e.window.showErrorMessage("File is not Camel Integration!") } })); n.subscriptions.push(o); var u = e.commands.registerCommand("karavan.jbang-run", (function () { for (var n = [], i = 0; i < arguments.length; i++)n[i] = arguments[i]; if (n && n.length > 0) if (n[0].path.startsWith("webview-panel/webview")) (s = yn.get(n[0].**fsPath**)) && kn(s); else { var s, a = t.readFileSync(r.resolve(n[0].**fsPath**)).toString("utf8"), o = bn(s = r.basename(n[0].**fspath**), a); o[0]?Bn(s):e.window.showErrorMessage("File is not Camel-K Integration!")}}));

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L61

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L62

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L79

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L80

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L85

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L86

....................................................................................................................................................................................................................................................................

{ case "save":  if (e.workspace.workspaceFolders) { var i = e.workspace.workspaceFolders[0].uri, s = **r.join(i.fsPath, n.filename)**; **e.window.showInformationMessage("Saving " +  s);** t.writeFile(s, n.yaml, (function (t) { t && e.window.showErrorMessage("Error: " + (null == t ? void 0 : t.message)) })) } return; 

https://github.com/apache/camel-karavan/blob/5376d574e7444320bac4903f7c1065cc75732853/karavan-vscode/src/extension.ts#L139

**Comment by mgubaidullin** [comment]
@gallfra-bh thanks. Would you mind to create a PR?
