### ISSUE TITLE
Editing of components with multiple path properties doesn't work correctly

### ISSUE THREAD

**Issue by ddoaj97** [apache/camel-karavan#730]
Many Camel component have more than one path parameter and currently the visual Karavan editor doesn't seem to handle these components very well. For example the Quartz component URI syntax is defined as  "quartz:groupName/triggerName" and contains two path parameters: "groupName" and "triggerName". Trying to configure these path properties in Karavan generates an incorrect URI because Karavan seems to mix up the two path properties.

Trying to enter the value "test" in the "Group name" input field of the Quartz component causes Karavan to generate the following URI:
![karavan_uri_path_bug_quartz](https://user-images.githubusercontent.com/17296796/233015685-4ba062e5-1724-4bfd-8146-1de839d141b4.PNG)

It seems like the first character of the "Group name" gets parsed into the "Trigger name" field and only the remaining characters end up in the "Group name" field. The problem disappears once both input fields have a value, but as soon as you clear the group name and enter a new value, then the same issue occurs again.

**I've tried other components that have multiple path properties (activemq, jms, rest, ftp, imap, ...) and they all have the same problem.**

Components with more than 2 path properties seem to be even more buggy. For example the "springws" component has 4 path properties and is completely unuseable. Trying to enter the value "expression" into the "Expression" input field seems to duplicate this value multiple times into the "Web Service Endpoint Uri" input field:
![karavan_uri_path_bug_springws](https://user-images.githubusercontent.com/17296796/233016014-fad0f3ce-0df2-4247-8156-70e2f8443824.PNG)

**Comment by davsclaus** [comment]
Thanks for reporting, and I assume you are using latest 3.20.1 release of karavan

**Comment by ddoaj97** [comment]
Hi Claus,

Yes, you are correct. I am using Karavan release 3.20.1

**Comment by LeeyCul** [comment]
Has this bug been unsolved yet

**Comment by LeeyCul** [comment]
It would be great if it could be repaired in a timely manner

**Comment by davsclaus** [comment]
This is more complex to resolve as its only a handful of camel components that have multiple paths, and building correct URIs is more tricky. There is code in pure java we use internally in Camel itself. But that code is big and a big ugly. However for karavan such kind of code may need to be ported to typescript.

ASF is open community and users are very welcome to help with the project.

**Comment by LeeyCul** [comment]
I tried and I don't know how to get started,Can you prioritize handling this bug？

**Comment by mgubaidullin** [comment]
@davsclaus could you please take a look https://issues.apache.org/jira/browse/CAMEL-19426

**Comment by LeeyCul** [comment]
This seems like there's no solution at all. 
// if (result.at(result.length - 1) === '') return result.slice(0, -2).join(''); // remove last colon
This just looks like the configuration is fine, but after switching the code, new issues will appear, with inconsistencies on both sides

**Comment by mgubaidullin** [comment]
@LeeyCul could you please provide an example of component that has an issue with configuration?

**Comment by LeeyCul** [comment]
@mgubaidullin 
When I create a new REST，
<img width="1094" alt="image" src="https://github.com/apache/camel-karavan/assets/31834149/22226958-1f80-4047-8680-a47aed4dea5e">
<img width="483" alt="image" src="https://github.com/apache/camel-karavan/assets/31834149/7537d612-eff6-4a8e-8d82-dbf56aeadfe3">
Will directly cause issues with the uri address

**Comment by mgubaidullin** [comment]
@davsclaus  to avoid all complexity you mentioned above, I'm planning to remove URI parser and generator in Karavan and set path parameters  same way as query parameters, ex:

```
- route:
    id: route-e06b
    from:
      uri: timer
      id: from-74ea
      parameters:
        timerName: timer1
      steps:
        - to:
            uri: activemq
            id: to-c229
            parameters:
              destinationType: topic
              destinationName: topic1
```

**Comment by LeeyCul** [comment]
@mgubaidullin Will version 3.20.2 remain unchanged?

**Comment by mgubaidullin** [comment]
@LeeyCul 3.20.2 comes with unified path and query parameters. Karavan will continue to read and parse path parameters from uri, but write only as key: value

**Comment by LeeyCul** [comment]
https://github.com/apache/camel-karavan/issues/730#issuecomment-1589959534
After following this modification, new issues have emerged：
Two new Directs have been created, named rest1 and rest2 respectively，Incorrect URI selection address after switching to REST new interface
<img width="1510" alt="image" src="https://github.com/apache/camel-karavan/assets/31834149/b2861bad-1a4f-4d33-8c7a-edc772c66ba6">
<img width="1500" alt="image" src="https://github.com/apache/camel-karavan/assets/31834149/f9127bad-174a-48ba-b7d2-9f6713c85ac8">
@mgubaidullin

**Comment by LeeyCul** [comment]
The correct value should be direct:rest1
