### ISSUE TITLE
Run or export integration failed on VS code (windows)

### ISSUE THREAD

**Issue by trickMin** [apache/camel-karavan#745]
I have create a integration on VS code, and I want to run(JBang run) or export integration but failed. Did I configure anything the wrong way? How can I solve this problem?

- I operated from these buttons
![image](https://user-images.githubusercontent.com/59214333/233920512-db0e74ca-8360-4dff-8ab6-b95f549b7d8e.png)
- JBANG run
![image](https://user-images.githubusercontent.com/59214333/233920143-09882d09-68ad-4dde-b1df-28ca8d6bdad9.png)
- export
![image](https://user-images.githubusercontent.com/59214333/233920079-e636a634-547f-41e0-a0c5-3f3ed776d8d4.png)

**Comment by davsclaus** [comment]
Hmm that is weird as `-D` is an option. Wonder if there is some clunky on windows when the key has dots.

**Comment by davsclaus** [comment]
Can you try to manually type in the terminal the -D with single quotes or double quotes

    jbang -D'camel.jbang.version=3.20.3' camel@apache/camel run *

Or

    jbang -D"camel.jbang.version=3.20.3" camel@apache/camel run *

**Comment by davsclaus** [comment]
And what version of jbang do you use

    jbang -V

**Comment by trickMin** [comment]
Actually I cannot remember, but I use command 'jbang version' and it's normally show '0.106.3' version, and also I can use jbang to run other Java class.
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Claus ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/24/2023 15:19
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [apache/camel-karavan] Run or export integration failed on VS code (windows) (Issue #745)
        
      
    
  

Have you installed jbang first?
https://www.jbang.dev/

**Comment by trickMin** [comment]
Thanks! It works well by using following command!  I think it's a bug of windows VS code karavan plugin executing using no "" or '' .jbang -D'camel.jbang.version=3.20.3' ***@***.***/camel run *Orjbang -D"camel.jbang.version=3.20.3" ***@***.***/camel run *
        
        
            
        
    
         
        
            
                        ***@***.***
            
        
     
    
  
    ---- Replied Message ----
  
  
    
      
        
         From 
        
        
            Claus ***@***.***>
            
        
      
      
        
         Date 
        
        
        4/24/2023 15:23
        
      
      
        
         To 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         Cc 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         Subject 
        
        
              Re: [apache/camel-karavan] Run or export integration failed on VS code (windows) (Issue #745)
        
      
    
  

Can you try to manually type in the terminal the -D with single quotes or double quotes
jbang -D'camel.jbang.version=3.20.3' ***@***.***/camel run *

Or
jbang -D"camel.jbang.version=3.20.3" ***@***.***/camel run *

**Comment by davsclaus** [comment]
@trickMin its hard to read your responses via email.

Do you mind typing/pasting the working command here on github as a comment

**Comment by trickMin** [comment]
Thanks! It works well by using following command!  

`jbang -D'camel.jbang.version=3.20.3' camel@apache/camel run *` or `jbang -D"camel.jbang.version=3.20.3" camel@apache/camel run *`

I think it's a bug of windows VS code Karavan plugin (powershell) executing using no "" or '' after `-D` option.

**Comment by davsclaus** [comment]
Okay but I think @mgubaidullin should make karavan use single quotes on the command to make it work out of the box on windows. Or in general.
