### ISSUE TITLE
Allow user to upload a jar file.

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#749]
Camel-jbang version 4 has the ability to export a jar file in the project folder to the local lib folder.  more details can be found at [camel-jbang](https://github.com/apache/camel-kamelets-examples/tree/main/jbang/local-jar) example
Add a UI feature in camel-karavn that can take a jar file and add it to the project.

Example camel-jbang command
```
jbang -Dcamel.jbang.version=4.0.0-SNAPSHOT camel@apache/camel  export  --runtime=spring-boot --gav=com.foo:acme:1.0
```

**Comment by mrinalsharma** [comment]
you can assign this to me.

**Comment by mgubaidullin** [comment]
@mrinalsharma could you please what are you trying to do?
1. Add jar file to the route as described in the https://github.com/apache/camel-kamelets-examples/tree/main/jbang/local-jar ?
2. Export project as maven using `jbang camel export`?

**Comment by mgubaidullin** [comment]
Export as a maven project has already implemented in Karavan VS Code extension
<img width="415" alt="Screenshot 2023-04-25 at 2 11 48 PM" src="https://user-images.githubusercontent.com/1379213/234366339-e04b2b91-6065-4e56-a4dc-0e28c367998d.png">

**Comment by mgubaidullin** [comment]
Karavan aimed to have the same experience in VS Code extension and in Cloud App.
Both work with code in Git repo. Actually the best practice is to keep projet code in Git repo.
External dependencies should be configured in `camel.jbang.dependencies` property

**Comment by mgubaidullin** [comment]
Library is not promoted to Maven - this is very bad practice. Project build is not reproducible.
Karavan aimes to provide best practices. Karavan VS Code and Cloud app should work same way.

**Comment by mrinalsharma** [comment]
understood,  but in practice, not all projects follow best practices..  some projects have legacy code whose artifacts are not in maven and libraries are stored in source controls.  These libraries are added as file dependencies.

Also, sometimes the dependent library is not fully developed to be published in public or private maven, there should still be an option for users to try and test the logic in such a library.  giving only the repository option,  user is forced to finish their library work first and publish to Maven. Then only he can consume.  This creates serialization of work and teams don't like serializing work.
What if user just has a stub API in the library initially from another team. They will publish the library later once it's tested.

**Comment by mgubaidullin** [comment]
1. Rare case and Very bad practice. 
2. Has workaround: copy jar somewhere, add to `camel.jbang.dependencies`, click `Karavan:export`

No reason to implement already legacy and bad practice approach in newly created tool.

**Comment by davsclaus** [comment]
> understood, but in practice, not all projects follow best practices.. some projects have legacy code whose artifacts are not in maven and libraries are stored in source controls. These libraries are added as file dependencies.
> 
> Also, sometimes the dependent library is not fully developed to be published in public or private maven, there should still be an option for users to try and test the logic in such a library. giving only the repository option, user is forced to finish their library work first and publish to Maven. Then only he can consume. This creates serialization of work and teams don't like serializing work. What if user just has a stub API in the library initially from another team. They will publish the library later once it's tested.

Yeah that was also one of the reasons for the local JAR feature in jbang. IMHO allowing users to just drop what they need in the same folder, and then let jbang figure out how to run this, and export nicely into working maven/gradle based projects that can be used to continue, and also for jenkins/ci-cd pipelines to build and deploy from there.

All in total making Karavan and Camel more approachable to users that want a quick and easy way to build small integrations and for users that need to prototype "stuff".

I would like to consider reopening this and be able to offer this feature.
