### ISSUE TITLE
[VSCode Extension] Lateral panel hides REST action

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#763]
When using a low resolution (or zoom-in view) with VS Code extension, the lateral panel with properties blocks the view to the REST action buttons on the left side.

![image](https://github.com/apache/camel-karavan/assets/1001939/e2c263d3-02bb-4ab8-9e0e-0816fb20d745)

**Comment by mgubaidullin** [comment]
Have you tried to resize?

![resize](https://github.com/apache/camel-karavan/assets/1379213/1c10e1f4-aa34-436a-ae95-a9fd031c0456)

**Comment by hguerrero** [comment]
I tried, but it looks like there is a minimum size for the panel:

![karavan-issue](https://github.com/apache/camel-karavan/assets/1001939/e2d32a49-e48c-46d6-839d-82454a748060)

**Comment by mgubaidullin** [comment]
```
defaultSize={'400px'}
maxSize={'800px'} 
minSize={'300px'}
```
