### ISSUE TITLE
Karavan Runner - Camel version in use

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#770]
Currently it uses 3.21.0-SNAPSHOT which is hardcoded in the dockerfile.

I think we should find a way to configure this, and also find a way to use the same Camel version as the project uses.

So if you create a Q or SB project then this version that they use as Camel, we should make the same version for the runner.
It will be easier when those projects are on 3.21 or better.

Also you may want to be able to configure a specific version, so maybe you can set the runner version in application.properties

**Comment by mgubaidullin** [comment]
It is hard-coded for development purposes only. It will be synchronized with Camel version across Karavan as soon as camel-jbang reload and upload released.

**Comment by mgubaidullin** [comment]
Also runner and builder images will be merged into one

**Comment by mgubaidullin** [comment]
And they will use camel-jbang as a BASE instead of pure jbang

**Comment by davsclaus** [comment]
okay perfect, yeah we need 3.21 SNAPSHOT due to changes needed in camel-core - so it will take a month or so still before its released. Let me just close this ticket then
