### ISSUE TITLE
EIPs with mandatory options not configured should show the name in red

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#784]
See the timer source that are in red because an option has not set.

When doing the same for EIPs like aggregator then its still in red.
<img width="1496" alt="Screenshot 2023-06-05 at 09 42 11" src="https://github.com/apache/camel-karavan/assets/477100/26ba8681-aac8-4bfa-bfe9-44da91e00c07">

**Comment by davsclaus** [comment]
Currently the EIP is in bold, but we could make it red instead

**Comment by mrinalsharma** [comment]
I can work on this.
