### ISSUE TITLE
Error while starting the application 'quarkus.oidc.auth-server-url' property must be configured 

### ISSUE THREAD

**Issue by manali-jambhale** [apache/camel-karavan#791]
while running the karavan-3.20.2-SNAPSHOT-runner.jar in local getting the error "quarkus.oidc.auth-server-url property must be configured" but the profile i'm trying to use is public. Any solutions for this?

<img width="404" alt="image" src="https://github.com/apache/camel-karavan/assets/113964244/cfed10f1-c93e-4f29-a82e-2537fcc0e512">

**Comment by mgubaidullin** [comment]
[quarkus.oidc.enabled](https://quarkus.io/guides/security-oidc-configuration-properties-reference#quarkus-oidc_quarkus.oidc.enabled) property is 'Fixed at build time`. Set profile at build time. Same way as in [Github Actions](https://github.com/apache/camel-karavan/blob/7918ed0d4ffa37557ea6885932f7aedc3b65d5c6/.github/workflows/app.yml#L69)
