### ISSUE TITLE
Karavan producing invalid YAML DSL when using un/marshal component

### ISSUE THREAD

**Issue by brunomendola** [apache/camel-karavan#799]
VS Code complains that the YAML code generated by Karavan is not valid against the [json schema](https://raw.githubusercontent.com/apache/camel/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json).

It's not just VS Code, the error is returned also when validating the YAML file against the schema programmatically.

I've seen cases where the validation error was just the case-sensitive matching of an enum; I don't know if it covers all the cases, so this issue is only about the component I've experienced the issue on.

i.e. when using the Marshal or Unmarshal components with the Jackson library, Karavan uses "jackson", but the schema would validate "Jackson" with the uppercase first letter.

![image](https://github.com/apache/camel-karavan/assets/1853562/b45003cc-ebd8-4da4-a546-959e34a914d6)

**Comment by mgubaidullin** [comment]
https://issues.apache.org/jira/browse/CAMEL-19471

**Comment by brunomendola** [comment]
When validating the YAML programmatically, I switched to the approach seen in [this test file](https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/test/groovy/org/apache/camel/dsl/yaml/deserializers/SplitTest.groovy), by using the deserializers contained in the camel-yaml-dsl module, and it works better than validating against the json schema, since the enum matching is done in case-insensitive mode.

But the VS Code issue remains...

**Comment by mgubaidullin** [comment]
karavan generates YAML using camelYamlDsl.sjon and camel catalog.
So as soon as this values be synchronized in camel itself karavan will start to generate correct values.
Issue in camel is open https://issues.apache.org/jira/browse/CAMEL-19471

**Comment by mgubaidullin** [comment]
Fixed in https://github.com/apache/camel-karavan/issues/810
