### ISSUE TITLE
Issues with onException clause

### ISSUE THREAD

**Issue by mvolf** [apache/camel-karavan#812]
Hi everyone,

I opened a discussion with the issue I'm facing, but got no replies. That's why I'm opening this issue and hoping I'll get some help/suggestions here.

### Discussed in https://github.com/apache/camel-karavan/discussions/811

<div type='discussions-op-text'>

<sup>Originally posted by **mvolf** June 29, 2023</sup>
Hi everyone,

I'm having issues with configuring onException for a route and thought I should first ask here, before opening an issue.
I created a simple route configuration with onException clause, but the resulting YAML fails with the following exception during the deployment:

```
Node should have only have 1 key, was: 3 keys: [exception,id,redeliveryPolicy] (Maybe this is an indent problem in the YAML source).
 in file:exensio-s3-loader.camel.yaml, line 3, column 9:
          - exception:
            ^
```

I didn't edit the YAML manually and the complete integration was created using the designer UI. This segment in the YAML was created as follows:

```
- routeConfiguration:
    onException:
      - exception:
          - java.lang.Throwable
        id: onException-f031
        redeliveryPolicy:
          id: redeliveryPolicy-b507
          maximumRedeliveries: 2
```

I looked at the Camel YAML DSL specification and to me everything looks correct.

Any suggestions would be more than welcome.</div>

**Comment by mgubaidullin** [comment]
@mvolf Apache Camel Karavan is a community project and we do not provide any SLA. 
If you need guaranteed response time, please contact a company from [this list ](https://camel.apache.org/manual/commercial-camel-offerings.html) that provide commercial support services for Apache Camel.

**Comment by mgubaidullin** [comment]
This issue was already fixed https://github.com/apache/camel-karavan/commit/7f24e49f578c7f892609856a83b3a343054463fe in the upcoming [3.20.2](https://github.com/apache/camel-karavan/milestone/3)

**Comment by mvolf** [comment]
@mgubaidullin I didn't want to be rude or request faster response times. I was simply not sure if the discussion is the right thing to use for the question I posted.
I apologise if it sounded like the above and thanks for the explanation and reply.
