### ISSUE TITLE
clone gitea - fails in tekton spring boot build task

### ISSUE THREAD

**Issue by git-josip** [apache/camel-karavan#823]
I am experiencing an issue when setting up camel-karavan locally with Minikube and docker. I  am using Ammple silicon but I do not believe the issue is happening because of that.  

Karavan starts normally and I successfully set up gitea, repository is working and I have created a repository which then is added to `karavan-cloud/minikube/karavan-secret.yaml` file with credentials. 
I create project and push changes to gitea, and I can see in gitea UI dashboard changes are there in the repository, new camel integration, and properties. 

Issue occurrs when I try to deploy it to k8s minikube cluster. Spring boot build job is started and I get follwoing error: 
```
fatal: could not read Username for 'http://192.168.65.254:3000': No such device or address
/tekton/scripts/script-0-9j2b7: line 15: cd: /scripts/testscheduler: No such file or directory
jbang -Dcamel.jbang.version=3.20.3 camel@apache/camel export --local-kamelet-dir=/scripts/kamelets
[jbang] Resolving dependencies...
[jbang]    org.apache.camel:camel-bom:3.20.3@pom
[jbang]    org.apache.camel:camel-jbang-core:3.20.3

```
git clone obviously fails with that strange error and later also fails `cd` command because there is no my project `testscheduler` . 

I tried using many different gitea deployments but no luck.  I had deployed gitea using docker-compose and lates was with k8s helm chart, but the error is always happening on that same step.  I have tried using bitbucket but I have same error.
I found similar old issue: 
https://github.com/tektoncd/pipeline/issues/1375

This is karavan tekton build task script: 
```
script: |
        #!/usr/bin/env bash
        CHECKOUT_DIR="/scripts"
        KAMELETS_DIR="/scripts/kamelets"
        
        if  [[ $GIT_REPOSITORY == https* ]] ;
        then
            replacer=https://$GIT_PASSWORD@
            prefix=https://
            url="${GIT_REPOSITORY/$prefix/$replacer}"
            git clone --depth 1 --branch ${GIT_BRANCH} $url ${CHECKOUT_DIR}
        else
            git clone --depth 1 --branch ${GIT_BRANCH} ${GIT_REPOSITORY} ${CHECKOUT_DIR}
        fi
     .....
     ......   
```

And error is happening on `git clone --depth 1 --branch ${GIT_BRANCH} ${GIT_REPOSITORY} ${CHECKOUT_DIR}` 

I do not know what else to do.

Thank you,
Josip

**Comment by mgubaidullin** [comment]
@git-josip could you please try with 3.21.0 ?

**Comment by mgubaidullin** [comment]
Starting from 4.0.0 Karavan does not use Tekton anymore
