### ISSUE TITLE
Upgrade to camel-kamelets 0.5.0

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#84]

**Comment by mgubaidullin** [comment]
@davsclaus  Could not find camel-kamelets-catalog 0.5.0 in maven repo https://repo.maven.apache.org/maven2/org/apache/camel/kamelets/camel-kamelets-catalog

**Comment by davsclaus** [comment]
Ah it will come when camel-k 1.7.0 is released

**Comment by davsclaus** [comment]
0.5.0 has been released

**Comment by mgubaidullin** [comment]
Fixed in https://github.com/apache/camel-karavan/pull/93
