### ISSUE TITLE
karavan-core tests fail on Windows

### ISSUE THREAD

**Issue by stefanhuber** [apache/camel-karavan#843]
I tried to setup a local dev environment on Windows and tried to follow the steps in `DEV.md`. When running `npm install` inside `karavan-core` the following error appears:

![grafik](https://github.com/apache/camel-karavan/assets/5379359/34a1965d-f54f-43d3-ae6b-2c6714ef2f25)

For folks working on Windows, git is often configured to replace `\n` with `\r\n`, thus tests would fail. The yaml files, which tests compares to have then the `\r\n` line endings...

**Comment by stefanhuber** [comment]
There are currently 4 occassions in the `karavan-core` project, which fail, due to the reason on Windows. A pragmatic solution would be to replace all `\r\n` with `\n`: `expect(yaml.replaceAll("\r\n", "\n")).to.equal(yaml2)`. Another idea would be to use deep equality and the parsed yaml representation: `expect(jsYaml.load(yaml)).to.deep.equal(jsYaml.load(yaml2))`. The first appraoch seems reasonable in this case?

**Comment by davsclaus** [comment]
You are welcome to send a PR with windows fixes so we can have this work for both linux and windows
