### ISSUE TITLE
Upgrade web app to Patternfly 5

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#851]
Depends on https://github.com/apache/camel-karavan/issues/833

**Comment by mgubaidullin** [comment]
Can't pass actions build because of https://github.com/patternfly/patternfly-react/issues/9466

**Comment by nicolethoen** [comment]
@mgubaidullin 

https://github.com/patternfly/patternfly-react/issues/9466 has been released as a patch and is included in the following promoted patternfly versions!
@patternfly/patternfly: 5.0.4
@patternfly/react-charts: 7.0.1
@patternfly/react-code-editor: 5.0.1
@patternfly/react-core: 5.0.1
@patternfly/react-icons: 5.0.1
@patternfly/react-styles: 5.0.1
@patternfly/react-table: 5.0.1
@patternfly/react-tokens: 5.0.1

Please let me know if you're still seeing the issue!

**Comment by mgubaidullin** [comment]
Thanks @nicolethoen
