### ISSUE TITLE
Runner and Builder images should include java 17

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#855]
Latest jbangdev/jbang-action:0.110.0 is still based on Java 11 and downloads java 17 on demand. It is too slow.

**Comment by davsclaus** [comment]
@maxandersen I wonder if jbang want to consider releasing images with JDK17 as base line as well ?

**Comment by mgubaidullin** [comment]
@davsclaus we need JBang and maven. 
It is simpler to install JBang so I used `maven:3.9.3-eclipse-temurin-17-alpine` as base image and install JBang ontop

**Comment by maxandersen** [comment]
I've made jbang-setup action if the usecase is for github actions. 

For base images; yes want to make multi images and have a prototype for it. 

But yeah - wouldn't include maven so your current solution is probably the same :)
