### ISSUE TITLE
Component picker - Show full description in tooltip or something

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#856]
The grid cut of the description for some components (eg ...) maybe if we have a tooltip that then shows the full description.

<img width="1169" alt="Screenshot 2023-08-11 at 13 02 12" src="https://github.com/apache/camel-karavan/assets/477100/3d02e7e4-f3a2-4f32-8144-c65d99790450">

PS: Its also a good way to change. the descriptions in Camel to be shorter, as some like the AWS have not useful details about ... using the AWS SDK Java 2 client.

**Comment by vijay31** [comment]
Hi @mgubaidullin 

This is easy to solve. All we need to do is wrap description under ToolTip component like following, 

`
<Tooltip content={dsl.description} position={TooltipPosition.bottom}>
       <Text className="pf-v5-u-color-200">{dsl.description}</Text>
</Tooltip>
`
Please assign this ticket to me, and I can push the fix for this.

**Comment by vijay31** [comment]
@mgubaidullin  please review the PR - https://github.com/apache/camel-karavan/pull/1300

**Comment by mgubaidullin** [comment]
Thanks @vijay31
