### ISSUE TITLE
‼️ Karavan secrets not found

### ISSUE THREAD

**Issue by zyzgreater** [apache/camel-karavan#881]
I am running the following problem is a prompt error, who can help to give a solution?
![image](https://github.com/apache/camel-karavan/assets/98529866/f6fa6645-1ae5-4b05-9b97-16a4efd4a069)

**Comment by mgubaidullin** [comment]
What is your environment: minikube, kubernetes or openshift?

**Comment by zyzgreater** [comment]
Adding the --image-registry=docker.io parameter solves that problem. However, a new problem occurred. It was loaded all the time while running, as shown in the figure. Moreover, the log of node I checked was empty, and the state of node was Pending.And I ran an nginx in my k8s to verify that my k8s was working.
![image](https://github.com/apache/camel-karavan/assets/98529866/1e4e0fee-7ace-4b3c-b089-6ebcc452d055)
![image](https://github.com/apache/camel-karavan/assets/98529866/399968d8-c41c-4bb2-aeb9-ae969d2993bf)
![image](https://github.com/apache/camel-karavan/assets/98529866/f85e3007-0108-433d-a94e-a4f107c55218)

**Comment by mgubaidullin** [comment]
https://kubernetes.io/docs/tasks/debug/debug-application/debug-pods/#my-pod-stays-pending

**Comment by zyzgreater** [comment]
![image](https://github.com/apache/camel-karavan/assets/98529866/26f3a312-3f73-4376-960c-117a71dc4b62)
I checked my configuration, it is 4 core 4G, 40G disk, and there is a lot of space left, because this centos I only run karavan. And I also used this command kubectl describe pods ${POD_NAME}, as shown in the figure.

**Comment by mgubaidullin** [comment]
Looks like your kubernetes could claim persistent volume required for Karavan 3.21.0

**Comment by mgubaidullin** [comment]
BTW. 4G of memory is definitely not enough even for kubernetes itself

**Comment by zyzgreater** [comment]
1. I exported karavan's yaml with pvc in it, then I manually created pv and it worked.

2. However, after I create a new container on the web, I still need to create a new pv, and deleting the container pvc will not disappear.

3. To make matters worse, 
[root@k8s-master ~]# kubectl logs hi-runner n karavan
[jbang] [ERROR] Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details
Ahh...

**Comment by zyzgreater** [comment]
![image](https://github.com/apache/camel-karavan/assets/98529866/f4047a31-e965-4ee5-a0c5-b054a4598769)
kubectl exec -it karavan-76b54C4699-wVBKV-n karavan -- /bin/bash 
or
 kubectl exec -it karavan-76B54C4699-wVBKV-n karavan -- /bin/sh

All into the container, so don't go to,
because I want to test whether can connect to the https://github.com/apache/camel/blob/HEAD/jbang-catalog.json.

Because I passed the test nginx is downloadable.

**Comment by zyzgreater** [comment]
It is really hard to understand why this error is prompted:

[root@k8s-master ~]# kubectl logs hi-runner n karavan
[jbang] [ERROR] Could not download https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details

I looked at the source code and didn't find this request

**Comment by zyzgreater** [comment]
I feel that I am going to succeed, please help me point out, thank you

**Comment by mgubaidullin** [comment]
Do you have this error when installing Karavan or when running integration in devmode or when building/deploying integration with pipeline?

**Comment by zyzgreater** [comment]
![image](https://github.com/apache/camel-karavan/assets/98529866/09fb0cb7-a432-49c4-b640-4b4d4d31cd96)
This is the full log of the startup of karavan

**Comment by zyzgreater** [comment]
2023-09-08 00:42:36,756 ERROR [org.apa.cam.kar.ser.GitService] (executor-thread-1) New repository 
2023-09-08 00:42:36,764 ERROR [org.apa.cam.kar.ser.GitService] (executor-thread-1) No HEAD exists and no explicit starting revision was specified
This is the only error. There are other caveats. But does this error message require me to set up some configuration in the git repository?

**Comment by zyzgreater** [comment]
Do you have any good ideas about the above error?

**Comment by mgubaidullin** [comment]
Could you please check that the default branch in the repo is the same as you have configured in secrets

**Comment by zyzgreater** [comment]
Does the branch still need to be configured for parameter passing? What parameters do I need to pass?

But does this error cause this error?
The 2023-09-08 00:42:36, 756 ERROR [org. Apa. CAM. Kar. Ser. GitService] (executor - thread - 1) New repository
The 2023-09-08 00:42:36, 764 ERROR [org. Apa. CAM. Kar. Ser. GitService] (executor - thread - 1) No HEAD exists and No explicit starting revision was specified

**Comment by mgubaidullin** [comment]
Can you try with 4.4.0?

**Comment by zyzgreater** [comment]
![image](https://github.com/apache/camel-karavan/assets/98529866/9ffedbc1-65e3-4f39-af36-e445b773adcf)
This is the configuration of my Docker-Compose, my Docker version is Docker version 26.0.0
![image](https://github.com/apache/camel-karavan/assets/98529866/65f7aabe-aa1a-4b2c-aec5-2b15dd39998b)
Follow this step to start, but create a simple timer project, and the log output continues to loop as follows
![image](https://github.com/apache/camel-karavan/assets/98529866/f96171ae-6cd0-48ff-9e91-b58a8c8cab72)

**Comment by zyzgreater** [comment]
Since the previous problem was not solved, I changed the method again, but gitea and karaven ran normally, but there were still problems, as shown in the following screenshot
![image](https://github.com/apache/camel-karavan/assets/98529866/555a9fa3-486a-40a5-adde-659399a49c82)
![image](https://github.com/apache/camel-karavan/assets/98529866/83ecd634-0944-434e-baac-0acd5957c85b)

**Comment by zyzgreater** [comment]
@mgubaidullin
