### ISSUE TITLE
URI path parameters matching bug

### ISSUE THREAD

**Issue by f-ambroz** [apache/camel-karavan#882]
The bug can be reproduced with all components that have more than one path parameter, e.g., github.

The problem is with path parameter matching.
The syntax for the component used in the example is "_github:**type**/**branchName**_"

Steps to reproduce:
1) Create a route and add a component with more than one path parameter.
![image](https://github.com/apache/camel-karavan/assets/139461769/0299f432-ee9b-490c-b3a3-061c662261ac)

2) Fill in the input fields for those path parameters.
![image](https://github.com/apache/camel-karavan/assets/139461769/8d254688-d9ed-4e20-9591-90b450b1fc5b)

3) Delete the value of one of the parameters.
![image](https://github.com/apache/camel-karavan/assets/139461769/f25aa1fe-0466-4280-b2e6-fbd6ff4a7618)

**Comment by davsclaus** [comment]
This is fixed in the 4.0.x releases
