### ISSUE TITLE
karavan:karavan-cli:jar:4.0.0-RC2 was not found in https://repo.maven.apache.org/maven2

### ISSUE THREAD

**Issue by victorchapman** [apache/camel-karavan#886]
I'm trying to follow the setup for the web version of karavan and when I try to install using the command below I receive this error.

mvn org.apache.maven.plugins:maven-dependency-plugin:3.0.2:copy -Dartifact=org.apache.camel.karavan:karavan-cli:4.0.0-RC2:jar -DoutputDirectory=. 
<img width="1505" alt="Screenshot 2023-09-11 at 10 50 00 AM" src="https://github.com/apache/camel-karavan/assets/65624008/c5b9e80b-3366-4d54-b8a4-2b76e8ac860b">

I'm using the brew version of mvn and I'm using a M1 macbook pro.
I also could not find the karavan folder on the site provided
https://repo.maven.apache.org/maven2

**Comment by mgubaidullin** [comment]
Karavan 4.x is not released yet. See releases: https://github.com/apache/camel-karavan/releases

**Comment by victorchapman** [comment]
Thanks for letting me know, You should fix your readme
<img width="1138" alt="Screenshot 2023-09-11 at 2 09 52 PM" src="https://github.com/apache/camel-karavan/assets/65624008/c37cef7b-e6fc-4c93-9e1d-502e0bc59f28">

**Comment by mgubaidullin** [comment]
We are welcome contributors!

**Comment by victorchapman** [comment]
@mgubaidullin One question, why does this error happen?
<img width="1509" alt="Screenshot 2023-09-11 at 2 32 38 PM" src="https://github.com/apache/camel-karavan/assets/65624008/c23f7916-91fd-43e2-8fc5-7793bda4f105">

**Comment by mgubaidullin** [comment]
You need to configure image registry.
Either set karavan-cli parameters or, if you use minikube, you could use internal registry by enabling add-on
