### ISSUE TITLE
UI BUG: I can't access the YAML DSL code when I click the toggler

### ISSUE THREAD

**Issue by victorchapman** [apache/camel-karavan#891]
When I toggle between Code and Design nothing changes otherwise everything works.
<img width="2559" alt="Screenshot 2023-09-12 at 2 33 10 PM" src="https://github.com/apache/camel-karavan/assets/65624008/bb51dea1-d757-48dc-8f9a-dfba52f5fcd7">

**Comment by victorchapman** [comment]
@mgubaidullin Does this feature work for you?

**Comment by mgubaidullin** [comment]
@victorchapman yes

**Comment by mgubaidullin** [comment]
Could you try 4.0.0 ?

**Comment by mvolf** [comment]
I can confirm that it works as expected on a local minikube deployment of 4.0.0.
