### ISSUE TITLE
Local setup - Developer guide steps not working

### ISSUE THREAD

**Issue by Hemanthone** [apache/camel-karavan#902]
The documented steps under https://github.com/apache/camel-karavan/blob/main/docs/DEV.md are not working on windows.
Example : The command in step 3:  "mvn clean package -f karavan-app -Dquarkus.profile=public " fails to execute.
Getting message:  
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] 'cp' is not recognized as an internal or external command,
[INFO] [io.quarkiverse.quinoa.deployment.packagemanager.PackageManager] operable program or batch file.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Please help resolve this issue in order to build Karavan UI and backend from source and be able to experiment with code changes.

**Comment by mgubaidullin** [comment]
if you're running on windows you have to replace "cp" with "copy"
