### ISSUE TITLE
Camel 4.1 - Bean Configuration - Add support for new constructors

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#905]
In Camel 4.1 we make it more tooling friendly to configure beans, such as constructors are now

```
- beans:
    - name: orderService
      type: "com.foo.OrderService"
      constructors:
        0: "true"
        1: "#bean:office"
```

The numbers are 0, 1, 2 as index for the constructor. 

There are plans for more, such as factory-method and start/stop methods.

**Comment by davsclaus** [comment]
PS: In Camel 4.0, you would need to do the example above as

```
- beans:
    - name: orderService
      type: "com.foo.OrderService(true, '#bean:office')"
```

**Comment by mgubaidullin** [comment]
@davsclaus why they called `constructors`? they are actually `constructorParameters`, no?

**Comment by davsclaus** [comment]
Yes but that is the naming convention we use (some places its called constructor-args)

**Comment by mgubaidullin** [comment]
I'm OK with `constructorArgs` as soon as they are in `camelCase` ;-)
