### ISSUE TITLE
Upgrade jib-maven-plugin

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#908]
When building then jib reports that there is a newer version

**Comment by mgubaidullin** [comment]
@davsclaus I think jib version is set in camel-jbang https://github.com/apache/camel/blob/a744ff06ad1cecdddf0ede435fd127db3aca57ca/dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl#L4

Perhaps we could make it as a property in `application.properties`

**Comment by davsclaus** [comment]
https://issues.apache.org/jira/browse/CAMEL-20026

**Comment by davsclaus** [comment]
This will require a new camel release so moving to 4.2.

**Comment by davsclaus** [comment]
You can now configure this and we use 3.4.0 as default version in Camel 4.2

**Comment by davsclaus** [comment]
You can configure in application.properties with key `camel.jbang.jib-maven-plugin-version`
