### ISSUE TITLE
JBang ERROR: Script or alias could not be found or read: '.jbang.version=3.21.0'

### ISSUE THREAD

**Issue by brunomendola** [apache/camel-karavan#910]
When running a YAML from VSCode for Windows, the following error occurs:
`[jbang] [ERROR] Script or alias could not be found or read: '.jbang.version=3.21.0'`

This is due to Karavan generating the jbang command without wrapping the JVM parameters in quotes, that is required under Powershell.

This is the command generated:
`jbang -Dcamel.jbang.version=3.21.0 camel@apache/camel run *`

This is what it should have been:
`jbang "-Dcamel.jbang.version=3.21.0" camel@apache/camel run *`

Follows screenshot:
![image](https://github.com/apache/camel-karavan/assets/1853562/517f028d-4c42-46a5-9d45-f0c92db8d6fd)

**Comment by davsclaus** [comment]
Thanks for reporting. I assume we could maybe just do that always as it also ought to work on linux/mac systems

**Comment by brunomendola** [comment]
I think so. It's mandatory for Powershell, but supported also in Linux/Mac.

I'm trying to make a pull request :)
