### ISSUE TITLE
Custom kamelets not sent to devmode container

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#913]

**Comment by thomas-gantenbein-tga** [comment]
@mgubaidullin, I think I see the problem: the script cds into the project directory, while line 2 assumes the kamelet to be in /scripts/kamelet, I. e. one level above: https://github.com/apache/camel-karavan/blob/14ee133855aaf8e47a5984bb13f3661f9e95dd51/karavan-web/karavan-app/src/main/resources/snippets/camel-main-builder-script-docker.sh#L21
