### ISSUE TITLE
Hope to support lower version of camel 3.14.9

### ISSUE THREAD

**Issue by Seifon** [apache/camel-karavan#919]
Hope to support lower version of camel

camel version: 3.14.9

java version: 1.8

 Because the company project is still using Java 1.8, we have to use the 3.14.9 version of the camel

 It would be even better if it could simultaneously support generating XML Dsl

**Comment by davsclaus** [comment]
Sorry karavan will only support newer versions, and the work is done for 4.x onwards now.

**Comment by davsclaus** [comment]
For generating XML then btw camel-jbang is coming with a new `camel transform` command that can convert Yaml DSL into XML DSL (Camel 4.1) - so potentially in the future it may be that this can be done as a "way" of making karavan do its YAML DSL, and then you can choose to transform to XML DSL in your project.
