### ISSUE TITLE
while trying to run mvn quarkus:dev

### ISSUE THREAD

**Issue by TonyCruez** [apache/camel-karavan#933]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.025 s
[INFO] Finished at: 2023-10-09T13:08:52+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'quarkus' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories/

**Comment by davsclaus** [comment]
What are you doing excatly. Can you write a more detailed report
