### ISSUE TITLE
OIDC auth profile doesn't refresh tokens

### ISSUE THREAD

**Issue by jwgmeligmeyling** [apache/camel-karavan#937]
When using ODIC the interface stops working after the access token expires. The refresh token doesn't seem to be used. After a hard refresh (and going through the OIDC challenge again) the interface works again.

Workaround: increase access token lifespan.

Tested in version V4.0.0.

Also: am I correct that the OIDC profile currently expects the realm to be "karavan" and the client ID to be "karavan-frontend" and that these are not dynamic? Couldn't find a way to set these so quickly.

**Comment by mgubaidullin** [comment]
#938

**Comment by mgubaidullin** [comment]
In the next release will be configurable:
```
karavan.keycloak.url=http://localhost:8079
karavan.keycloak.realm=karavan
karavan.keycloak.frontend.clientId=frontend
karavan.keycloak.backend.clientId=backend
karavan.keycloak.backend.secret=secret
```
