### ISSUE TITLE
Karavan Space - Route configuration does not work

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#945]
When I add onException and any of the others, then the UI show a tiny box but I cannot configure anything, see picture
<img width="2076" alt="Screenshot 2023-10-21 at 12 53 46" src="https://github.com/apache/camel-karavan/assets/477100/dc4bbaf2-8960-4240-90a3-aff6bfdf96c0">

**Comment by mgubaidullin** [comment]
related to this https://github.com/apache/camel-karavan/issues/931
