### ISSUE TITLE
Kamelet with missing description

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#948]
The 4.0.1 release of this kamelet has description in the yaml
https://github.com/apache/camel-kamelets/blob/v4.0.1/kamelets/aws-sqs-fifo-sink.kamelet.yaml

But in Karavan it seems that there is no description
<img width="1122" alt="Screenshot 2023-10-22 at 14 44 59" src="https://github.com/apache/camel-karavan/assets/477100/d4a8d7f7-29d6-4096-b3be-c6fd3e853095">

**Comment by mgubaidullin** [comment]
Kamelets description might be quite long.
In selector we show only the first line of description.
Unfortunately this Kamelet has the first line in description empty.

I will add the checker for line emptiness, 
however I would prefer to have Kamelet description without empty first line.
