### ISSUE TITLE
Standalone loads all YAML file from directory

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#95]
When using the Standalone application in LOCAL mode, it reads all the YAML files in the integrations folder as Integrations even if those files represent something else.

Maybe we need a validation that the `Kind:` is correct, or parse a schema perhaps?

**Comment by davsclaus** [comment]
Ah yeah in the top there is a way to see if its Camel, and kind integration / kameletbinding

**Comment by mgubaidullin** [comment]
There is no more standalone app
