### ISSUE TITLE
Complete cleanup not being done on project delete

### ISSUE THREAD

**Issue by mvolf** [apache/camel-karavan#951]
I've noticed that after deleting the project, the container remains active and the project still runs in it.
Currently it's not clear to the user that the project container will stay active and become an "orphan". This can cause unnecessary load on the system, since the resources are being used by the deleted projects.

With Karavan 4 we have a "Containers" page where we're able to manually delete the containers, but I think that user should be more aware that deleting the project doesn't do a full cleanup.

My opinion is that Karavan should have an option (checkbox) to stop and delete project containers on deleting the project itself.

**Comment by mgubaidullin** [comment]
Related https://github.com/apache/camel-karavan/issues/551

**Comment by mgubaidullin** [comment]
@mvolf looks like you are actively using Karavan web application.
If you don't mind I would like to know more about your experience.
Please contact me by email marat@apache.org
