### ISSUE TITLE
After Installation the Create Intergration takes for ever

### ISSUE THREAD

**Issue by srinivasks22** [apache/camel-karavan#970]
Type: <b>Bug</b>

Karavan plugin installed successfully. I clicked on create integration, punched in abc.camel.yaml and that's it. I see a spinner taking for ever.

[Extension Host] [node.js fs] readdir with filetypes failed with error:  Error: ENOENT: no such file or directory, scandir '/undefined'
$ @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:456
Q @ rpcProtocol.ts:441
M @ rpcProtocol.ts:371
L @ rpcProtocol.ts:297
(anonymous) @ rpcProtocol.ts:161
z @ event.ts:1138
fire @ event.ts:1169
fire @ ipc.net.ts:650
Y.onmessage @ localProcessExtensionHost.ts:581
console.ts:137 [Extension Host] EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, scandir '/undefined'
	at E.e (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:26740)
	at Object.readDirectory (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:127:24744)
	at async ss (/Users/a3109213/.vscode/extensions/camel-karavan.karavan-4.0.0/dist/extension.js:2:750396)
	at async /Users/a3109213/.vscode/extensions/camel-karavan.karavan-4.0.0/dist/extension.js:2:750100
	at async ns (/Users/a3109213/.vscode/extensions/camel-karavan.karavan-4.0.0/dist/extension.js:2:750058)
	at async Promise.all (index 3)

Extension version: 4.0.0
VS Code version: Code 1.83.1 (Universal) (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:46:55.789Z)
OS version: Darwin arm64 21.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id eebe64c4-dbcc-4939-8def-99ecdf9a943b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
vscrp:30673768
a9j8j154:30646983
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingt:30859503
asynctok:30869155
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixtcf:30871695
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet00cf:30874137
pythontbext0:30864172

```

</details>

**Comment by mgubaidullin** [comment]
You need to open a Folder in VS Code before creating Integration

**Comment by srinivasks22** [comment]
Thank you, it worked.

**Comment by davsclaus** [comment]
closing as working now
