### ISSUE TITLE
Karavan dev builder Service Account default permission issue

### ISSUE THREAD

**Issue by skumaravelan** [apache/camel-karavan#974]
I tried adding ingress.jkube.yaml and try to build the integration , failed with 403 forbidden issue.
I tried to update the jkube to use different ServiceAccount which has a permission to perform
resource creation failed as it was still referencing Karavan Service account.
When we need to create ingress,mapping and vip. We need Karavan to have those create permission.
Please add those privileges as needed . 
also need a way to configure Service account which we could use as a alternative.

**Comment by skumaravelan** [comment]
Does this take care of other resources like mapping and custom resources?

**Comment by mgubaidullin** [comment]
There are a lot of different implementation of ingress and they required different permissions.
https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/

Karavan service account now has the following permission resources `"endpoints", "ingresses", "ingressclasses", "endpointslices"` verbs `*`
