### ISSUE TITLE
Karavan Web - Unable to scroll to bottom of the properties

### ISSUE THREAD

**Issue by dpalinic** [apache/camel-karavan#975]
Hi @mgubaidullin , thanks for your effort building and maintaining such a cool tool. 

Properties for some components are impossible to reach (scroll). For example, http and https component have long list of properties, and Security and Advanced options are not visible.

![image001](https://github.com/apache/camel-karavan/assets/801314/ea9c3445-cb04-4e98-abec-5c879e828c05)

Same issue is on the UI Builder side (where Add new Route and Add Route configuration buttons are not accessible)

![signal-2023-11-02-142325_003](https://github.com/apache/camel-karavan/assets/801314/44cd4684-4fa7-44b3-aede-fad18f70fc9f)

Tested on version 4.1.

**Comment by mgubaidullin** [comment]
It does not look like 4.1.
1. There is no 'Download Image' button in 4.1
2. There is no huge white empty space between header with filename + 'Run' button  and Designer tabs (routes, rest, beans)

**Comment by dpalinic** [comment]
Hi @mgubaidullin , sorry, my bad.  

I copy pasted a command from https://github.com/apache/camel-karavan/blob/4.1.0/docs/WEB_DOCKER.md and haven't noticed that command contains 4.0.0. version instead of the 4.1.0

docker run -it --rm  --name karavan \
    --network karavan -p 8080:8080 \
    -e KARAVAN_GIT_INSTALL_GITEA=true \
    -e KARAVAN_IMAGE_REGISTRY_INSTALL=true \
    -v /var/run/docker.sock:/var/run/docker.sock \
    **ghcr.io/apache/camel-karavan:4.0.0**

On 4.1.0 works well.
