### ISSUE TITLE
Karavan Web - Can't add Namespace for xpath expression in Set Property integration pattern

### ISSUE THREAD

**Issue by dpalinic** [apache/camel-karavan#983]
How to reproduce:
1. Create integration file
2. Add Set Property integration pattern using UI builder
3. Select xpath for language
4. Click + Add namespace button below a Namespace
5. Observe no input field is displayed

![image](https://github.com/apache/camel-karavan/assets/801314/d0fa6afe-16fc-4df4-abaf-6d8655ae5be3)

**Comment by mgubaidullin** [comment]
Fixed
