### ISSUE TITLE
Karavan Web - Component Vert.x HTTP Client is displaying beans for Http Method dropdown

### ISSUE THREAD

**Issue by dpalinic** [apache/camel-karavan#986]
How to reproduce:
1. Create integration
2. Add http vert.x client
3. Try setting Http Method
4. Observe that beans list is displayed instead of GET, POST, PUT, DELETE etc. list

![Selection_895](https://github.com/apache/camel-karavan/assets/801314/3eb4255c-5b55-47f9-b316-4b39628d0f16)

**Comment by mgubaidullin** [comment]
1. Karavan generates properties from Camel YAML DSL Schema and Camel-Catalog.
2. Http Method of Vert.x HTTP Client in Camel Catalog is defined as `"type": "object", "javaType": "io.vertx.core.http.HttpMethod"` https://github.com/apache/camel/blob/363e7e1c93f61e23cdae808f2180908169c78f6e/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/vertx-http.json#L60C1-L61C1

@davsclaus anything we could do to make it user friendly?

**Comment by davsclaus** [comment]
Yes we can add enums for those so tooling can show a nice list of values.
https://issues.apache.org/jira/browse/CAMEL-20102
