### ISSUE TITLE
Standalone mode - 0.0.6 in web ui and 0.0.7 in quarkus

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#99]
Running the latest standalone mode in JVM via docker and noticed the version number difference.

**Comment by mgubaidullin** [comment]
Fixed for now in https://github.com/apache/camel-karavan/commit/86e26285272273b23a55db26d947c7832726804b 
and closed in a favour of https://github.com/apache/camel-karavan/issues/106
