### ISSUE TITLE
How to use custom processor in Karavan - Still throwing NoSuchBeanException

### ISSUE THREAD

**Issue by srinivasks22** [apache/camel-karavan#999]
### Discussed in https://github.com/apache/camel-karavan/discussions/818

<div type='discussions-op-text'>

<sup>Originally posted by **mgubaidullin** July  6, 2023</sup>
![custom-processor](https://github.com/apache/camel-karavan/assets/1379213/704ca671-ef97-4033-85f6-f4cab8039dc8)
</div>

<img width="1647" alt="Screen Shot 2023-11-18 at 8 45 39 AM" src="https://github.com/apache/camel-karavan/assets/2183549/33b09814-6cbd-4f7b-afac-4394194f6e8a">

**Comment by srinivasks22** [comment]
After a bit of research, appears to be weird but by specifying the below under the Processor component worked!!!

**Ref* = #class:org.camel.karavan.demo.openapi.DeleteUserById1** 

<img width="405" alt="Screen Shot 2023-11-18 at 9 27 13 AM" src="https://github.com/apache/camel-karavan/assets/2183549/61d44109-3d3f-4281-bf1d-62207ddc2246">


instead of

Red* = DeleteUserById1

**Comment by srinivasks22** [comment]
Now I'm trying to deploy this into Openshift and I see the below error as part of export

INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[9,2] cannot find symbol
  symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[10,2] cannot find symbol
  symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[9,2] cannot find symbol
  symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[10,2] cannot find symbol
  symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[9,2] cannot find symbol
  symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[10,2] cannot find symbol
  symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[9,2] cannot find symbol
  symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[10,2] cannot find symbol
  symbol: class Named
[INFO] 16 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.401 s
[INFO] Finished at: 2023-11-18T09:54:27-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project openapi: Compilation failure: Compilation failure: 
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[9,2] cannot find symbol
[ERROR]   symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/DeleteUserById1.java:[10,2] cannot find symbol
[ERROR]   symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[9,2] cannot find symbol
[ERROR]   symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetAllUsers1.java:[10,2] cannot find symbol
[ERROR]   symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[9,2] cannot find symbol
[ERROR]   symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/CreateNewUser1.java:[10,2] cannot find symbol
[ERROR]   symbol: class Named
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[6,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[7,20] package javax.inject does not exist
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[9,2] cannot find symbol
[ERROR]   symbol: class Singleton
[ERROR] /Users/a3109213/Desktop/DEV-HOME/WORKSPACE/Karavan/restservice/.export/src/main/java/org/camel/karavan/demo/openapi/GetUserById1.java:[10,2] cannot find symbol
[ERROR]   symbol: class Named
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

<img width="1087" alt="Screen Shot 2023-11-18 at 9 56 53 AM" src="https://github.com/apache/camel-karavan/assets/2183549/2fce4e13-8e14-44ac-9525-d67990cd8a2d">

**Comment by srinivasks22** [comment]
Continued by research and it took a while but finally figured out that the Quarkus latest version that I'm using in my project is out of sync with the example on the gihub. 

Latest Quarkus apparently has been migrated from javax.* to jakarata.* I changed all my java classes and their packages accordingly and now I'm able to deploy the code into openshift without any issues.

Man it took me a while to figure out as I'm fairly new to jBang, Quarkus, Karvana.

**Comment by srinivasks22** [comment]
Closing the ticket as I was able to accomplish what I need to.

**Comment by MN-Dheeraj** [comment]
> After a bit of research, appears to be weird but by specifying the below under the Processor component worked!!!
> 
> __Ref_ = #class:org.camel.karavan.demo.openapi.DeleteUserById1_*
> 
> <img alt="Screen Shot 2023-11-18 at 9 27 13 AM" width="405" src="https://private-user-images.githubusercontent.com/2183549/284004440-61d44109-3d3f-4281-bf1d-62207ddc2246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNDQ0MjksIm5iZiI6MTcxMzM0NDEyOSwicGF0aCI6Ii8yMTgzNTQ5LzI4NDAwNDQ0MC02MWQ0NDEwOS0zZDNmLTQyODEtYmYxZC02MjIwN2RkYzIyNDYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTdUMDg1NTI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjcwNGY2Y2M4M2FmMTFhNjAzN2M1MGIxMGIzODA3ODNiZjdhN2QzYzk1ZTNlMTRiYTI4ZTRlZTA0ODUxMDk0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jQFi7gx_q6wyVWzcysQ9ZIBzdD2m10r61jXR18Q5J-s">
> instead of
> 
> Ref* = DeleteUserById1

Hi. Does this resolve this issue? I created my own custom processor and just pointed to it using #class:package:classname.
But, it gets rendered as a new class not the one I wanted it refer to.
